//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbarStokTalep
    {
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public System.DateTime OnayTarihi { get; set; }
        public int TalepEdilenAmbarId { get; set; }
        public int AktarilacakAmbarId { get; set; }
        public decimal Miktar { get; set; }
        public int StokKartId { get; set; }
        public int KayitYapan { get; set; }
        public int OnayVeren { get; set; }
        public int TalepDurumu { get; set; }
        public long AmbarStokKartHareketId { get; set; }
        public int TigerAmbarId { get; set; }
    }
}
