//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbarStokKartHareket
    {
        public long Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int StokKartId { get; set; }
        public int AmbarStokKartId { get; set; }
        public int AmbarHareketTipi { get; set; }
        public decimal Miktar { get; set; }
        public int PtksFisNo { get; set; }
        public int PtksSiraNo { get; set; }
        public int UserId { get; set; }
        public string Aciklama { get; set; }
    }
}
