//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medya
    {
        public int Id { get; set; }
        public int BagliOlduguTip { get; set; }
        public int BagliOlduguId { get; set; }
        public string FileName { get; set; }
        public string MedyaAdi { get; set; }
    }
}
