//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriyotTanim
    {
        public int Id { get; set; }
        public int PeriyotTipi { get; set; }
        public int PeriyotDonemi { get; set; }
        public string PeriyotTanimAdi { get; set; }
        public string RenkSecimi { get; set; }
    }
}
