//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POTA_BOTAEntities : DbContext
    {
        public POTA_BOTAEntities()
            : base("name=POTA_BOTAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SystemBaseUrlLink> SystemBaseUrlLinks { get; set; }
        public virtual DbSet<SystemLinkGrupTanim> SystemLinkGrupTanims { get; set; }
        public virtual DbSet<SystemModul> SystemModuls { get; set; }
        public virtual DbSet<SystemRoleBaseUrlLink> SystemRoleBaseUrlLinks { get; set; }
        public virtual DbSet<SystemRoleTanim> SystemRoleTanims { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Bolum> Bolums { get; set; }
        public virtual DbSet<Departman> Departmen { get; set; }
        public virtual DbSet<PeriyotTanim> PeriyotTanims { get; set; }
        public virtual DbSet<PeriyotTipiTanim> PeriyotTipiTanims { get; set; }
        public virtual DbSet<KomponentTanim> KomponentTanims { get; set; }
        public virtual DbSet<KomponentTanimGrup> KomponentTanimGrups { get; set; }
        public virtual DbSet<TalimatGrupTanim> TalimatGrupTanims { get; set; }
        public virtual DbSet<TalimatTanim> TalimatTanims { get; set; }
        public virtual DbSet<SicilOzellikHeaderTanim> SicilOzellikHeaderTanims { get; set; }
        public virtual DbSet<SicilOzellikTanim> SicilOzellikTanims { get; set; }
        public virtual DbSet<SablonGrup> SablonGrups { get; set; }
        public virtual DbSet<SablonGrupItem> SablonGrupItems { get; set; }
        public virtual DbSet<StokKart> StokKarts { get; set; }
        public virtual DbSet<StokKartSicilOzellik> StokKartSicilOzelliks { get; set; }
        public virtual DbSet<StokKartKomponent> StokKartKomponents { get; set; }
        public virtual DbSet<KomponentTalimatGrup> KomponentTalimatGrups { get; set; }
        public virtual DbSet<KomponentTalimat> KomponentTalimats { get; set; }
        public virtual DbSet<StokKartOperasyon> StokKartOperasyons { get; set; }
        public virtual DbSet<StokKartOperasyonDurumTanim> StokKartOperasyonDurumTanims { get; set; }
        public virtual DbSet<Medya> Medyas { get; set; }
        public virtual DbSet<BilesenCinsi> BilesenCinsis { get; set; }
        public virtual DbSet<BilesenCinsiGrup> BilesenCinsiGrups { get; set; }
        public virtual DbSet<StokKartBilesenCinsi> StokKartBilesenCinsis { get; set; }
        public virtual DbSet<StokKartHatirlatma> StokKartHatirlatmas { get; set; }
        public virtual DbSet<Ambar> Ambars { get; set; }
        public virtual DbSet<DurusTipiTanim> DurusTipiTanims { get; set; }
        public virtual DbSet<StokKartDuru> StokKartDurus { get; set; }
        public virtual DbSet<DurusGrubuTanim> DurusGrubuTanims { get; set; }
        public virtual DbSet<ViewEksikAmbarListe> ViewEksikAmbarListes { get; set; }
        public virtual DbSet<ViewEksikListeStokKart> ViewEksikListeStokKarts { get; set; }
        public virtual DbSet<AmbarStokKart> AmbarStokKarts { get; set; }
        public virtual DbSet<AmbarStokKartAdre> AmbarStokKartAdres { get; set; }
        public virtual DbSet<AmbarStokKartHareket> AmbarStokKartHarekets { get; set; }
        public virtual DbSet<AmbarTipiTanim> AmbarTipiTanims { get; set; }
        public virtual DbSet<AmbarStokTalepDurumuTanim> AmbarStokTalepDurumuTanims { get; set; }
        public virtual DbSet<StokKartOperasyonKullanilanMalzeme> StokKartOperasyonKullanilanMalzemes { get; set; }
        public virtual DbSet<AmbarHareketTipiTanim> AmbarHareketTipiTanims { get; set; }
        public virtual DbSet<AmbarStokTalep> AmbarStokTaleps { get; set; }
    
        public virtual ObjectResult<SpEksikPersonelListe_Result> SpEksikPersonelListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpEksikPersonelListe_Result>("SpEksikPersonelListe");
        }
    
        public virtual ObjectResult<SpRoleLinkleri_Result> SpRoleLinkleri(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpRoleLinkleri_Result>("SpRoleLinkleri", roleIdParameter);
        }
    
        public virtual ObjectResult<SpAmbarStokGetir_Result> SpAmbarStokGetir(string stokKodu, string lotNo)
        {
            var stokKoduParameter = stokKodu != null ?
                new ObjectParameter("stokKodu", stokKodu) :
                new ObjectParameter("stokKodu", typeof(string));
    
            var lotNoParameter = lotNo != null ?
                new ObjectParameter("lotNo", lotNo) :
                new ObjectParameter("lotNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAmbarStokGetir_Result>("SpAmbarStokGetir", stokKoduParameter, lotNoParameter);
        }
    
        public virtual ObjectResult<SpAmbarStoklar_Result> SpAmbarStoklar(string ambarNo)
        {
            var ambarNoParameter = ambarNo != null ?
                new ObjectParameter("ambarNo", ambarNo) :
                new ObjectParameter("ambarNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpAmbarStoklar_Result>("SpAmbarStoklar", ambarNoParameter);
        }
    }
}
