//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareket
    {
        public int FisNo { get; set; }
        public int SiraNo { get; set; }
        public string StokTuru { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string SeriNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public string OlcuBirimi1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<decimal> Miktar3 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<short> SiparisSiraNo { get; set; }
        public string PartiNo { get; set; }
        public string IslemGrubu { get; set; }
        public string Aciklama { get; set; }
        public string SatinalmaSiparisNo { get; set; }
        public Nullable<short> SatinalmaSiparisSiraNo { get; set; }
        public Nullable<short> IslemSiraNo { get; set; }
        public string DaraTipNo { get; set; }
        public string KDVDahilmi { get; set; }
        public Nullable<decimal> KDVOrani { get; set; }
        public Nullable<decimal> BrutNetKatsayisi { get; set; }
        public Nullable<decimal> Kur { get; set; }
        public Nullable<decimal> YerelFiyat { get; set; }
        public string PaletNo { get; set; }
        public Nullable<short> UretimSiraNo { get; set; }
        public string CariLotNo { get; set; }
        public string MaliyetMerkezNo { get; set; }
        public string Kabul { get; set; }
        public Nullable<int> BagliOlduguFisNo { get; set; }
        public Nullable<int> BagliOlduguSiraNo { get; set; }
        public Nullable<int> DokumSiraNo { get; set; }
        public Nullable<System.DateTime> TanimlandigiTarih { get; set; }
        public Nullable<int> SevkIsEmriNo { get; set; }
        public Nullable<System.DateTime> DokumTarihi { get; set; }
        public Nullable<int> SevkiyatPlanNo { get; set; }
    }
}
