//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokAmbarAdre
    {
        public int SiraNo { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string AmbarNo { get; set; }
        public string SeriNo { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public decimal Miktar1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public Nullable<decimal> Miktar3 { get; set; }
    }
}
