//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartOperasyonKullanilanMalzeme
    {
        public int Id { get; set; }
        public int OperasyonId { get; set; }
        public int KullanilanStokKartId { get; set; }
        public decimal Miktar { get; set; }
        public int KullanilanAmbar { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public long AmbarStokKartHareketId { get; set; }
        public int KayitYapanId { get; set; }
    }
}
