//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartKomponent
    {
        public int Id { get; set; }
        public int StokKartId { get; set; }
        public int BagliOlduguStokKartId { get; set; }
        public int KomponentTanimId { get; set; }
        public bool SeciliMi { get; set; }
        public int Miktar { get; set; }
    }
}
