//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKart
    {
        public int Id { get; set; }
        public int KomponentTanimId { get; set; }
        public string PotaId { get; set; }
        public string LogoId { get; set; }
        public string StokTanimAdi { get; set; }
        public string StokKodu { get; set; }
        public string SeriNo { get; set; }
        public string ImageUrl { get; set; }
        public int KomponentTanimGrupId { get; set; }
        public int SablonGrupId { get; set; }
        public int BolumId { get; set; }
        public string SicilNo { get; set; }
        public string LotNo { get; set; }
        public bool SeciliMi { get; set; }
    }
}
