//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartOperasyon
    {
        public int Id { get; set; }
        public int StokKartId { get; set; }
        public System.DateTime PlanlananTarih { get; set; }
        public System.DateTime GerceklesenTarih { get; set; }
        public int KomponentTalimatGrupId { get; set; }
        public int OperasyonDurumu { get; set; }
        public int PlanlananHafta { get; set; }
        public int GerceklesenHafta { get; set; }
        public System.DateTime IlkPlanlananTarih { get; set; }
        public int KayitYapanId { get; set; }
        public string YapilanTalimatlarStr { get; set; }
    }
}
