//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketAna
    {
        public int FisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public string FisTuru { get; set; }
        public string GirisAmbarNo { get; set; }
        public string CikisAmbarNo { get; set; }
        public string CariNo { get; set; }
        public string Aciklama { get; set; }
        public string BelgeTuru { get; set; }
        public string BelgeNo { get; set; }
        public Nullable<System.DateTime> BelgeTarihi { get; set; }
        public string FisiDuzenleyen { get; set; }
        public string SevkYeri { get; set; }
        public string NakliyeFirmasi { get; set; }
        public string WayBill { get; set; }
        public string SevkSiparisNo { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public Nullable<byte> HareketKarakteri { get; set; }
        public Nullable<double> BeyanEdilenMiktar { get; set; }
        public string OtomatikBelgeNo { get; set; }
        public string SayacKarakteri { get; set; }
        public int SonKayitNo { get; set; }
        public Nullable<decimal> BeyanEdilenMiktar2 { get; set; }
        public Nullable<decimal> BeyanEdilenMiktar3 { get; set; }
        public string GidecegiAmbarNo { get; set; }
        public string SozlesmeNo { get; set; }
        public Nullable<System.DateTime> TanimlandigiTarih { get; set; }
        public Nullable<int> LogoAktarim { get; set; }
        public Nullable<System.DateTime> AktarimHataTarihSaat { get; set; }
        public string AktarimHata { get; set; }
    }
}
