//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBota.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemBaseUrlLink
    {
        public int Id { get; set; }
        public int LinkGrupTanimId { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string LinkTanimAdi { get; set; }
        public string LinkTanimAdiEng { get; set; }
        public int DetayLinkDurumu { get; set; }
    }
}
