//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_SARFKONTROL_ALTERNATIFUALISTESI
    {
        public string StokKodu { get; set; }
        public string BilesenStokKodu { get; set; }
        public decimal KullanimMiktari { get; set; }
        public Nullable<decimal> FireYuzde { get; set; }
        public short UrunAgaciAlternatif { get; set; }
    }
}
