//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_CARITAKIP_KARSILIKSIZCEKKAPATMA
    {
        public int KarsiliksizID { get; set; }
        public int OdemeHareketID { get; set; }
        public Nullable<decimal> CekTutarKapatilan { get; set; }
        public Nullable<decimal> HareketTutarKapatan { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
