//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_MakineTakip_IsListesi
    {
        public string MakineGrubu { get; set; }
        public string MakineNo { get; set; }
        public Nullable<System.DateTime> IslemBaslamaTarihi { get; set; }
        public string RefakatNo { get; set; }
        public Nullable<System.DateTime> ProgramTarihi { get; set; }
        public Nullable<decimal> PartiMiktar { get; set; }
        public Nullable<decimal> ToplamBildirim { get; set; }
        public string SiparisNo { get; set; }
        public short SipSiraNo { get; set; }
        public string CariAdi { get; set; }
        public Nullable<int> BolumAdedi { get; set; }
        public Nullable<short> CalisanBolumAdedi { get; set; }
        public Nullable<decimal> StandartSure { get; set; }
        public string REFPARTINO { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<decimal> KalanSaat { get; set; }
        public Nullable<System.DateTime> DurusBaslama { get; set; }
        public string DurusNedenAdi { get; set; }
    }
}
