//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_ARABALAR
    {
        public string SeriNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string PersonelNo { get; set; }
        public string ArabaNo { get; set; }
        public string StokKodu { get; set; }
        public string RefakatNo { get; set; }
        public string RefPartiNo { get; set; }
        public Nullable<int> IslemSiraNo { get; set; }
        public Nullable<int> UretimSiraNo { get; set; }
        public Nullable<decimal> NetKg { get; set; }
        public string BobinTipi { get; set; }
        public Nullable<int> BobinAdedi { get; set; }
        public Nullable<int> YarimBobinAdedi { get; set; }
        public Nullable<int> GirisFisNo { get; set; }
        public Nullable<int> GirisFisSiraNo { get; set; }
    }
}
