//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_OTOPAKETLEMESARF_SARFOLACAKBILDIRIMLER_BOBIN
    {
        public Nullable<int> SNO { get; set; }
        public string SeriNo { get; set; }
        public Nullable<System.DateTime> TanimlandigiTarih { get; set; }
        public string StokKodu { get; set; }
        public string PartiNo { get; set; }
        public Nullable<short> IslemSiraNo { get; set; }
        public Nullable<short> UretimSiraNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public string SozlesmeNo { get; set; }
    }
}
