//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_DARATIP_KG_MAX
    {
        public string DaraTipNo { get; set; }
        public string DaraTipAdi { get; set; }
        public Nullable<decimal> MaxKg { get; set; }
        public Nullable<decimal> MinKg { get; set; }
    }
}
