//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_AUTOMAIL
    {
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Subject1 { get; set; }
        public string Receipent { get; set; }
        public string Body1 { get; set; }
        public string Body2 { get; set; }
        public string Body3 { get; set; }
        public string Body4 { get; set; }
        public string Body5 { get; set; }
        public string Body6 { get; set; }
        public string Body7 { get; set; }
        public int SiraNo { get; set; }
        public Nullable<System.DateTime> GonderimTarihi { get; set; }
    }
}
