//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACIK_SARFKONTROL_UA4
    {
        public string StokKodu { get; set; }
        public string C4_BT { get; set; }
        public string C4_BK { get; set; }
        public string C4_BA { get; set; }
        public Nullable<decimal> C4_KM { get; set; }
        public Nullable<decimal> C4_FY { get; set; }
    }
}
