//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbalajTip
    {
        public string AmbalajTipNo { get; set; }
        public string AmbalajTipAdi { get; set; }
        public string DaraTipNo { get; set; }
        public Nullable<decimal> En { get; set; }
        public Nullable<decimal> Boy { get; set; }
        public Nullable<decimal> Yukseklik { get; set; }
    }
}
