//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambalaj
    {
        public string AmbalajNo { get; set; }
        public string AmbalajSeriNo { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string PaletNo { get; set; }
    }
}
