//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbarAdres
    {
        public string AmbarNo { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public Nullable<decimal> XBoyut { get; set; }
        public Nullable<decimal> YBoyut { get; set; }
        public Nullable<decimal> ZBoyut { get; set; }
        public Nullable<decimal> MaxKapasite { get; set; }
        public string Aciklama { get; set; }
    }
}
