//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambar
    {
        public string AmbarNo { get; set; }
        public string AmbarAdi { get; set; }
        public string TicariAmbarNo { get; set; }
        public string Adresleme { get; set; }
        public string SevkiyatYapilabilirmi { get; set; }
        public string RezervasyonYapilabilirmi { get; set; }
        public string OtomasyonVarmi { get; set; }
        public bool KullanimdaMi { get; set; }
        public bool MRPdeKulanilacak { get; set; }
        public bool ManuelHareketYapilamaz { get; set; }
        public string AmbarGrubu { get; set; }
        public string StokSiralamaYontemi { get; set; }
    }
}
