//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmortismanHareket
    {
        public int AmortismanHareketID { get; set; }
        public System.DateTime AmortismanTarihi { get; set; }
        public string SabitKiymetKodu { get; set; }
        public int HesapPlaniID { get; set; }
        public decimal Tutar { get; set; }
        public int FinansHareketAnaID { get; set; }
    }
}
