//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BakimIsEmri
    {
        public string BakimIsEmriNo { get; set; }
        public Nullable<System.DateTime> BildirimTarihi { get; set; }
        public Nullable<System.DateTime> PlanTarihi { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string BakimNo { get; set; }
        public string MakineNo { get; set; }
        public string Sonuc { get; set; }
        public Nullable<System.DateTime> KapatmaTarihi { get; set; }
        public string Kapatan { get; set; }
        public string Aciklama { get; set; }
        public string CalisanPersonelNo1 { get; set; }
        public string CalisanPersonelNo2 { get; set; }
        public string CalisanPersonelNo3 { get; set; }
        public Nullable<int> StokHareketAnaFisNo { get; set; }
    }
}
