//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankaSube
    {
        public int BankaSubeID { get; set; }
        public string SubeKodu { get; set; }
        public string SubeAdi { get; set; }
        public int BankaID { get; set; }
        public string Adres { get; set; }
        public string UlkeAdi { get; set; }
        public Nullable<int> IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public string PostaKodu { get; set; }
        public string FaksUlkeKodu { get; set; }
        public string FaksAlanKodu { get; set; }
        public string FaksNo { get; set; }
        public string TelefonNo1UlkeKodu { get; set; }
        public string TelefonNo1AlanKodu { get; set; }
        public string TelefonNo1 { get; set; }
        public Nullable<int> TelefonNo1HatSayisi { get; set; }
        public string TelefonNo2UlkeKodu { get; set; }
        public string TelefonNo2AlanKodu { get; set; }
        public string TelefonNo2 { get; set; }
        public Nullable<int> TelefonNo2HatSayisi { get; set; }
        public string Ilgili { get; set; }
        public string EMail { get; set; }
        public string SubeKullanimda { get; set; }
        public string SubeSwiftKodu { get; set; }
    }
}
