//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaskiVaryant
    {
        public string DesenNo { get; set; }
        public string VaryantNo { get; set; }
        public string VaryantSahibi { get; set; }
        public Nullable<System.DateTime> IlkCalismaTarihi { get; set; }
        public Nullable<decimal> CalisilanUretimHizi { get; set; }
        public Nullable<decimal> CalisilanNumuneMt { get; set; }
        public string Aciklama { get; set; }
        public string ReceteNo { get; set; }
        public string BaskiIslemTuru { get; set; }
        public string ZeminRengi { get; set; }
        public string RenkKodu { get; set; }
        public string DesenDosyaAdresi { get; set; }
        public string Kalite { get; set; }
        public string DuzenleyenNo { get; set; }
    }
}
