//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BordroKalem
    {
        public string IsyeriKodu { get; set; }
        public string BordroKalemTuru { get; set; }
        public int BordroKalemNo { get; set; }
        public string KalemAdi { get; set; }
        public string DigerAdi { get; set; }
    }
}
