//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BordroIsyeri
    {
        public string IsyeriKodu { get; set; }
        public string IsyeriUnvani { get; set; }
        public Nullable<System.DateTime> KurulusTarihi { get; set; }
        public string TicaretSicilNo { get; set; }
        public string IsKurBirimi { get; set; }
        public string SSKNo { get; set; }
        public string SSKSektor { get; set; }
        public string SSKMeslek { get; set; }
        public string SSKSube { get; set; }
        public string SSKDosyaNo { get; set; }
        public string SSKIl { get; set; }
        public string SSKIlce { get; set; }
        public string BolgeCalismaNo { get; set; }
        public string YapilanIs { get; set; }
        public string SSKSubeAdi { get; set; }
        public Nullable<byte> IsKodu { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiHesapNo { get; set; }
        public string TasarrufNo { get; set; }
        public string BankaSube { get; set; }
        public string BankaHesap { get; set; }
        public string TehlikeDerecesi { get; set; }
        public Nullable<double> TehlikeSinifi { get; set; }
        public Nullable<double> TehlikeOrani { get; set; }
        public string SinifOrani { get; set; }
        public Nullable<double> IsKazaMeslekHastalikOrani { get; set; }
        public Nullable<double> GunlukAylikCalismaSaati { get; set; }
        public Nullable<double> MadenMalullukIsVerenOrani { get; set; }
        public Nullable<double> MadenIsHatalariOrani { get; set; }
    }
}
