//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrodeDesenParametre
    {
        public int ParametreNo { get; set; }
        public string ParametreAdi { get; set; }
        public string Deger { get; set; }
        public string OlcuBirimi { get; set; }
        public bool Zorunlu { get; set; }
        public string Aciklama { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaAlanAdi { get; set; }
        public bool Erisim { get; set; }
        public int AlanTipi { get; set; }
    }
}
