//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrodeDesen
    {
        public string DesenNo { get; set; }
        public string MakineTipi { get; set; }
        public string DesenTipi { get; set; }
        public string DesenRaporu { get; set; }
        public string DesenGrubu { get; set; }
        public string DesenAltGrubu { get; set; }
        public string DesenUrunGrubu { get; set; }
        public string VersiyonNo { get; set; }
        public string ResimAdresi { get; set; }
        public Nullable<bool> KullanimdaMi { get; set; }
        public string Aciklama { get; set; }
    }
}
