//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ButceUretimTahmin
    {
        public string DonemAdi { get; set; }
        public string ButceStokGrubu { get; set; }
        public Nullable<decimal> TahminiUretimMiktari { get; set; }
        public Nullable<decimal> R1TahminiUretimMiktari { get; set; }
        public Nullable<decimal> R2TahminiUretimMiktari { get; set; }
        public Nullable<decimal> R3TahminiUretimMiktari { get; set; }
        public Nullable<decimal> FiiliUretimMiktari { get; set; }
    }
}
