//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalismamaNedeni
    {
        public string NedenNo { get; set; }
        public string NedenAdi { get; set; }
        public string Sekil { get; set; }
        public string Renk { get; set; }
    }
}
