//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariGorusmeler
    {
        public int CariGorusmelerID { get; set; }
        public Nullable<int> CariGorusmeTuruID { get; set; }
        public string CariNo { get; set; }
        public string CariAdiSoyadi { get; set; }
        public string GorusmeKonusu { get; set; }
        public Nullable<System.DateTime> GorusmeTarihiBaslangic { get; set; }
        public Nullable<System.DateTime> GorusmeTarihiBitis { get; set; }
        public string GorusenPersonelNo { get; set; }
        public string GorusmeAciklama { get; set; }
        public Nullable<int> CariGorusmeSonucID { get; set; }
        public Nullable<System.DateTime> EylemTarihi { get; set; }
        public Nullable<int> CariGorusmelerEylemPlaniID { get; set; }
    }
}
