//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariBordro
    {
        public int CariBordroID { get; set; }
        public Nullable<int> FinansIslemTurID { get; set; }
        public string CariNo { get; set; }
        public Nullable<int> BankaHesaplarimID { get; set; }
        public string BordroNo { get; set; }
        public Nullable<System.DateTime> BordroTarihi { get; set; }
        public string BordroAciklama { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<int> BagliIslemID { get; set; }
        public string IslemYeri { get; set; }
        public string KayitIslemTuru { get; set; }
        public Nullable<int> OrtalamaVadeGun { get; set; }
        public Nullable<System.DateTime> OrtalamaVadeTarih { get; set; }
    }
}
