//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariCekSenetDetay
    {
        public int CariCekSenetDetayID { get; set; }
        public Nullable<int> CariCekSenetID { get; set; }
        public string CekSenetDurumu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> FinansIslemTurID { get; set; }
        public Nullable<int> IslemFisiID { get; set; }
    }
}
