//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariIslemlerAna
    {
        public int CariIslemlerAnaID { get; set; }
        public Nullable<int> FinansIslemTurID { get; set; }
        public string FisNo { get; set; }
        public Nullable<System.DateTime> CariIslemTarihi { get; set; }
        public string CariIslemAciklama { get; set; }
        public Nullable<double> ToplamYerelBorc { get; set; }
        public Nullable<double> ToplamYerelAlacak { get; set; }
        public Nullable<int> BagliIslemID { get; set; }
        public string IslemYeri { get; set; }
    }
}
