//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariAdres
    {
        public string CariNo { get; set; }
        public string CariAdres1 { get; set; }
        public string UlkeKodu { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Bolge { get; set; }
        public string Adres { get; set; }
        public string PostaKodu { get; set; }
        public string TelUlkeKodu { get; set; }
        public string TelAlanKodu { get; set; }
        public string Tel { get; set; }
        public Nullable<int> TelHatNo { get; set; }
        public string FaxUlkeKodu { get; set; }
        public string FaxAlanKodu { get; set; }
        public string Fax { get; set; }
        public string FaturaAdresimi { get; set; }
        public string Semt { get; set; }
        public string FirmaUnvani { get; set; }
        public string Ilgili { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string ElektronikPosta { get; set; }
    }
}
