//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariIslemler
    {
        public int CariIslemlerID { get; set; }
        public Nullable<int> CariIslemlerAnaID { get; set; }
        public string CariNo { get; set; }
        public Nullable<double> YerelBorc { get; set; }
        public Nullable<double> YerelAlacak { get; set; }
        public Nullable<double> DovizliBorc { get; set; }
        public Nullable<double> DovizliAlacak { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<double> DovizKuru { get; set; }
        public string MakbuzNo { get; set; }
        public Nullable<int> OdemePlaniID { get; set; }
        public string IslemAciklama { get; set; }
        public string KurFarkiDovizBirimi { get; set; }
        public Nullable<double> KDVOrani { get; set; }
        public Nullable<int> BagliDetayIslemID { get; set; }
        public Nullable<System.DateTime> KapatilmaTarihi { get; set; }
        public string ButceKalemi { get; set; }
    }
}
