//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cek
    {
        public int CekID { get; set; }
        public int CekKasasiID { get; set; }
        public string PortfoyNo { get; set; }
        public System.DateTime Vade { get; set; }
        public string SeriNo { get; set; }
        public string Borclu { get; set; }
        public string MuhabirSube { get; set; }
        public string OdemeYeri { get; set; }
        public decimal DovizliTutar { get; set; }
        public string DovizBirimi { get; set; }
        public decimal Kur { get; set; }
        public decimal YerelTutar { get; set; }
        public int CekTipi { get; set; }
        public string CekDurumu { get; set; }
        public Nullable<int> BankaID { get; set; }
        public Nullable<int> BankaSubeID { get; set; }
        public string HesapNo { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> SonFinansHareketAnaID { get; set; }
        public int KendiCekimizID { get; set; }
        public string DevirCekDurumu { get; set; }
        public string GelenCariNo { get; set; }
        public string GidenCariNo { get; set; }
        public Nullable<int> GidenBankaHesaplarimID { get; set; }
        public bool DevirCeki { get; set; }
        public string ResimDosyaAdresi { get; set; }
    }
}
