//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CozguRapor
    {
        public string CozguRaporu { get; set; }
        public Nullable<int> ToplamTelAdedi { get; set; }
        public Nullable<byte> UretimBantAdedi { get; set; }
        public Nullable<decimal> BantGenisligi { get; set; }
        public string CozguRaporAdi { get; set; }
        public string Aciklama { get; set; }
        public string Karisim { get; set; }
        public Nullable<decimal> RaporBoyu { get; set; }
        public Nullable<int> CozguRaporSablonID { get; set; }
        public Nullable<decimal> LuvertEni { get; set; }
    }
}
