//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CozguRaporDetay
    {
        public string CozguRaporu { get; set; }
        public short AnaGrup { get; set; }
        public short AltGrup { get; set; }
        public short SiraNo { get; set; }
        public string IplikStokKodu { get; set; }
        public short TelAdedi { get; set; }
        public decimal Siklik { get; set; }
        public short AltGrupTekrarSayisi { get; set; }
        public short AnaGrupTekrarSayisi { get; set; }
        public string CozguRaporAdi { get; set; }
        public string KenarTipi { get; set; }
    }
}
