//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokuman
    {
        public string DokumanNo { get; set; }
        public string DokumanAdi { get; set; }
        public string DokumanTuru { get; set; }
        public string DokumanSinifi { get; set; }
        public Nullable<System.DateTime> YayinlamaTarihi { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public string YenilemeSikligi { get; set; }
        public Nullable<System.DateTime> SonGecerlilikTarihi { get; set; }
        public string Sahibi { get; set; }
        public string MaliyetMerkezNo { get; set; }
        public string Aciklama { get; set; }
        public string AramaAnahtarlari { get; set; }
        public string KopyalamaDetayNo { get; set; }
        public string Gecersiz { get; set; }
        public string SayacKodu { get; set; }
        public Nullable<int> KayitSiraNo { get; set; }
        public Nullable<int> ArsivSuresi { get; set; }
        public Nullable<System.DateTime> IptalTarihi { get; set; }
        public string IptalEden { get; set; }
        public string IptalNedeni { get; set; }
    }
}
