//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DurusNedeni
    {
        public string DurusNedenNo { get; set; }
        public string DurusNedenAdi { get; set; }
        public string DurusTipi { get; set; }
        public string Grubu { get; set; }
        public Nullable<bool> Randiman1 { get; set; }
        public Nullable<bool> Randiman2 { get; set; }
        public string OtomasyonDurusNedenNo { get; set; }
        public string Renk { get; set; }
        public string OtomasyondaKullaniliyormu { get; set; }
        public Nullable<bool> MakineKapali { get; set; }
        public bool RefakatKartiKapansinmi { get; set; }
    }
}
