//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntegrasyonProgram
    {
        public int EntegrasyonProgramID { get; set; }
        public string EntegrasyonProgramAdi { get; set; }
        public string ProgramVersiyonu { get; set; }
        public string FirmaNo { get; set; }
        public string DonemNo { get; set; }
        public string KullaniciKodu { get; set; }
        public string Sifre { get; set; }
        public string AktarimAdresi { get; set; }
        public Nullable<bool> CalisilanProgram { get; set; }
        public string Aciklama { get; set; }
    }
}
