//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaAna
    {
        public int FaturaAnaID { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public string CariNo { get; set; }
        public string Aciklama { get; set; }
        public string AmbarNo { get; set; }
        public string AmbarAdres { get; set; }
        public Nullable<double> KDVsizBrutTutar { get; set; }
        public Nullable<double> KDVsizNetTutar { get; set; }
        public Nullable<double> KDVliTutar { get; set; }
        public Nullable<double> IskontoOrani { get; set; }
        public Nullable<double> IskontoTutari { get; set; }
        public Nullable<int> FinansIslemTurID { get; set; }
        public string FisiDuzenleyenNo { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public Nullable<System.DateTime> KapatilmaTarihi { get; set; }
        public Nullable<int> EkMaliyetFaturaAnaID { get; set; }
    }
}
