//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int FaturaID { get; set; }
        public Nullable<int> FaturaAnaID { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string SeriNo { get; set; }
        public Nullable<double> Miktar1 { get; set; }
        public string OlcuBirimi1 { get; set; }
        public Nullable<double> Miktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<double> Miktar3 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public Nullable<double> YerelBirimFiyat { get; set; }
        public Nullable<double> YerelToplamBrutFiyat { get; set; }
        public Nullable<double> YerelToplamNetFiyat { get; set; }
        public Nullable<double> YerelKDVliToplamFiyat { get; set; }
        public Nullable<double> DovizliBirimFiyat { get; set; }
        public Nullable<double> DovizliToplamBrutFiyat { get; set; }
        public Nullable<double> DovizliToplamNetFiyat { get; set; }
        public Nullable<double> DovizliKDVliToplamFiyat { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<double> Kur { get; set; }
        public string KDVlidenIskonto { get; set; }
        public Nullable<double> DetayIskontoOrani { get; set; }
        public Nullable<double> YerelIskontoTutari { get; set; }
        public Nullable<double> DovizliIskontoTutari { get; set; }
        public string KDVDahilmi { get; set; }
        public Nullable<double> KDVOrani { get; set; }
        public Nullable<double> YerelKDVTutari { get; set; }
        public Nullable<double> DovizliKDVTutari { get; set; }
        public string DetayAciklama { get; set; }
        public string IrsaliyedenFatura { get; set; }
        public string SatinAlmadanFatura { get; set; }
        public string SatisdanFatura { get; set; }
        public Nullable<int> FisNo { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public byte FaturayaEsasAlinanMiktar { get; set; }
        public Nullable<double> TevkifatOrani { get; set; }
        public Nullable<double> YerelTevkifatTutari { get; set; }
        public Nullable<double> DovizliTevkifatTutari { get; set; }
        public string ButceKalemi { get; set; }
    }
}
