//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansHareket
    {
        public int FinansHareketID { get; set; }
        public int FinansHareketAnaID { get; set; }
        public int FinansKayitIslemYeriKodu { get; set; }
        public int HesapPlaniID { get; set; }
        public string BorcAlacak { get; set; }
        public decimal DovizliTutar { get; set; }
        public string DovizBirimi { get; set; }
        public decimal Kur { get; set; }
        public decimal YerelTutar { get; set; }
        public decimal Miktar { get; set; }
        public Nullable<int> FinansBelgeTurID { get; set; }
        public string BelgeNo { get; set; }
        public string ButceKalemi { get; set; }
        public string Aciklama { get; set; }
        public string CariNo { get; set; }
        public Nullable<int> KasaKartiID { get; set; }
        public Nullable<int> BankaHesaplarimID { get; set; }
        public Nullable<int> CariBankaSubeHesapID { get; set; }
        public Nullable<int> CekID { get; set; }
        public Nullable<int> SenetID { get; set; }
        public string VergiKodu { get; set; }
        public string GelirGiderKodu { get; set; }
        public string KurTipi { get; set; }
        public string StokMuhasebeGrubu { get; set; }
        public Nullable<int> KrediID { get; set; }
        public Nullable<System.DateTime> KrediTaksitVadeTarihi { get; set; }
        public string TevkifatOrani { get; set; }
        public Nullable<System.DateTime> KapatmaTarihi { get; set; }
    }
}
