//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansIslemTurEntegrasyon
    {
        public int FinansIslemTurEntegrasyonID { get; set; }
        public string FinansIslemTurKodu { get; set; }
        public int SiraNo { get; set; }
        public int FinansKayitIslemYeriKodu { get; set; }
        public string BorcAlacak { get; set; }
        public bool ZorunluBilgi { get; set; }
        public bool TekKayit { get; set; }
        public string GelirGiderKodu { get; set; }
        public int SecimSQLNo { get; set; }
        public string SQLAnalizNolari { get; set; }
        public bool MaliyetMerkeziGirisi { get; set; }
        public string Aciklama { get; set; }
    }
}
