//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansFaturaVergiOran
    {
        public int FinansFaturaVergiOranID { get; set; }
        public int FinansFaturaID { get; set; }
        public string VergiKodu { get; set; }
        public decimal VergiOrani { get; set; }
        public decimal VergiTutari { get; set; }
        public bool KDV { get; set; }
        public decimal YerelFaturaVergiTutari { get; set; }
        public decimal DovizliFaturaVergiTutari { get; set; }
        public Nullable<int> HesapPlaniID { get; set; }
    }
}
