//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansFaturaKapatma
    {
        public int FinansFaturaAnaID { get; set; }
        public int FinansHareketAnaID { get; set; }
        public int FinansHareketID { get; set; }
        public decimal DovizliTutar { get; set; }
        public string DovizBirimi { get; set; }
        public decimal Kur { get; set; }
        public decimal YerelTutar { get; set; }
        public decimal OdemeDovizliTutar { get; set; }
        public string OdemeDovizBirimi { get; set; }
        public decimal OdemeKur { get; set; }
        public decimal OdemeYerelTutar { get; set; }
        public Nullable<System.DateTime> KapatmaTarihi { get; set; }
        public string KapatanKullaniciKodu { get; set; }
        public int FinansHareketIDKapanan { get; set; }
    }
}
