//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansHareketAna
    {
        public int FinansHareketAnaID { get; set; }
        public int FinansDonemi { get; set; }
        public string FisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public string FinansIslemTurKodu { get; set; }
        public Nullable<int> MuhasebeFisTuruID { get; set; }
        public Nullable<int> YevmiyeNo { get; set; }
        public Nullable<int> FinansBelgeTurID { get; set; }
        public string BelgeNo { get; set; }
        public Nullable<int> OrtalamaVadeGun { get; set; }
        public Nullable<System.DateTime> OrtalamaVadeTarih { get; set; }
        public int FinansOzelKodID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> KilitlemeTarihi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public System.DateTime DegistirilmeTarihi { get; set; }
        public string DegistirenKullaniciKodu { get; set; }
        public string IhracatDosyaNo { get; set; }
        public Nullable<System.DateTime> BeyannameTarihi { get; set; }
    }
}
