//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansHareketMasrafMerkezi
    {
        public int FinansHareketID { get; set; }
        public string MaliyetMerkezNo { get; set; }
        public decimal DovizliTutar { get; set; }
        public decimal YerelTutar { get; set; }
        public string Aciklama { get; set; }
        public string MasrafTuru { get; set; }
    }
}
