//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinansIslemGrubu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinansIslemGrubu()
        {
            this.FinansIslemTuru = new HashSet<FinansIslemTuru>();
        }
    
        public string FinansIslemGrupKodu { get; set; }
        public string FinansIslemGrubu0 { get; set; }
        public string FinansIslemGrubu1 { get; set; }
        public string FinansIslemGrubu2 { get; set; }
    
        public virtual FinansIslemYeri FinansIslemYeri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinansIslemTuru> FinansIslemTuru { get; set; }
    }
}
