//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FisTurleri
    {
        public string FisTuru { get; set; }
        public string FisTurAdi { get; set; }
        public string HareketTipi { get; set; }
        public string Grubu { get; set; }
        public string TicariFisTuru { get; set; }
        public string Aciklama { get; set; }
        public string AlisSatis { get; set; }
        public string KontrolluMu { get; set; }
        public string TicariFisTurKodu { get; set; }
        public bool IskontoHesabiYap { get; set; }
        public string TicariHareketTipi { get; set; }
        public Nullable<int> FasonIslem { get; set; }
        public string BelgeTuru { get; set; }
        public bool Dogrulama { get; set; }
    }
}
