//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiyatListe
    {
        public string FiyatListeNo { get; set; }
        public short SiraNo { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string OdemeSekli { get; set; }
        public string TeslimSekli { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> IskontoyaEsasMiktar { get; set; }
        public Nullable<decimal> IskontoYuzdesi { get; set; }
        public Nullable<decimal> Fiyat2 { get; set; }
        public string DovizBirimi2 { get; set; }
        public Nullable<decimal> Fiyat3 { get; set; }
        public string DovizBirimi3 { get; set; }
        public string NakliyeSekli { get; set; }
        public Nullable<int> OnMaliyetSiraNo { get; set; }
        public string IslemGrubu { get; set; }
        public string PaketlemeSekli { get; set; }
        public string UstStokCariNo { get; set; }
    }
}
