//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAlanTanim
    {
        public int FormAlanTanimID { get; set; }
        public Nullable<int> FormTanimID { get; set; }
        public string AlanAdi { get; set; }
        public string Baslik0 { get; set; }
        public string Baslik1 { get; set; }
        public string Baslik2 { get; set; }
        public Nullable<int> KolonNo { get; set; }
    }
}
