//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelirVergisi
    {
        public string IsyeriKodu { get; set; }
        public Nullable<double> Deger1 { get; set; }
        public Nullable<double> Oran1 { get; set; }
        public Nullable<double> Deger2 { get; set; }
        public Nullable<double> Oran2 { get; set; }
        public Nullable<double> Deger3 { get; set; }
        public Nullable<double> Oran3 { get; set; }
        public Nullable<double> Deger4 { get; set; }
        public Nullable<double> Oran4 { get; set; }
        public Nullable<double> Deger5 { get; set; }
        public Nullable<double> Oran5 { get; set; }
        public Nullable<double> Deger6 { get; set; }
        public Nullable<double> Oran6 { get; set; }
        public Nullable<double> Deger7 { get; set; }
        public Nullable<double> Oran7 { get; set; }
        public Nullable<double> Deger8 { get; set; }
        public Nullable<double> Oran8 { get; set; }
        public string Yil { get; set; }
    }
}
