//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GKKAna
    {
        public string KontrolNo { get; set; }
        public System.DateTime KontrolTarihi { get; set; }
        public string KontroluYapan { get; set; }
        public string Aciklama { get; set; }
        public string StokTuru { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public int GirisFisNo { get; set; }
        public byte GirisFisSatirNo { get; set; }
        public decimal Miktar1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string KontrolSonucu { get; set; }
        public string RedHataKodu { get; set; }
        public string DokumanAdresi { get; set; }
        public string KaliteKodu { get; set; }
        public string KaliteAciklama { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string GKKDurum { get; set; }
    }
}
