//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grup
    {
        public int GrupID { get; set; }
        public string GrupAdi { get; set; }
        public string Kisiler { get; set; }
        public string Aciklama { get; set; }
        public string KullaniciKodu { get; set; }
        public string AktifPasif { get; set; }
    }
}
