//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HataliUretimHareket
    {
        public string RefakatKartNo { get; set; }
        public short SiraNo { get; set; }
        public int UretimSiraNo { get; set; }
        public int HSiraNo { get; set; }
        public string HataNedeni { get; set; }
        public Nullable<decimal> HataMiktari { get; set; }
    }
}
