//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazirlikHareket
    {
        public int HazirlikHareketID { get; set; }
        public string RefakatKartNo { get; set; }
        public Nullable<short> IslemSiraNo { get; set; }
        public string MakineNo { get; set; }
        public string PersonelNo { get; set; }
        public string HazirlikTipi { get; set; }
        public Nullable<System.DateTime> HazirlikBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> HazirlikBitisTarihi { get; set; }
    }
}
