//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapPlaniHesapTipi
    {
        public int HesapTipiKodu { get; set; }
        public string HesapTipi0 { get; set; }
        public string HesapTipi1 { get; set; }
        public string HesapTipi2 { get; set; }
    }
}
