//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapSQLleri
    {
        public int HesapSQLleriID { get; set; }
        public string HesapSQLAdi { get; set; }
        public string HesapSQLi { get; set; }
        public string Aciklama { get; set; }
        public bool Calistir { get; set; }
    }
}
