//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapPlani
    {
        public int HesapPlaniID { get; set; }
        public int FinansDonemi { get; set; }
        public string HesapKodu { get; set; }
        public string HesapAdi { get; set; }
        public string HesapGrubu { get; set; }
        public string MuhasebeBirimGrupKodu { get; set; }
        public string AnaGrupKodu { get; set; }
        public string AnaGrupAciklama { get; set; }
        public string GrupKodu { get; set; }
        public string GrupAciklama { get; set; }
        public string DovizBirimi { get; set; }
        public string DonemAdi { get; set; }
        public int CalismaSekliKodu { get; set; }
        public int BakiyeSekliKodu { get; set; }
        public int HesapTipiKodu { get; set; }
        public string OzelAlan1 { get; set; }
        public string OzelAlan2 { get; set; }
        public string OzelAlan3 { get; set; }
        public string OzelAlan4 { get; set; }
        public string OzelAlan5 { get; set; }
        public string OzelAlan6 { get; set; }
        public string OzelAlan7 { get; set; }
        public string OzelAlan8 { get; set; }
        public string OzelAlan9 { get; set; }
        public string OzelAlan10 { get; set; }
        public bool MuavinGoster { get; set; }
        public bool KurDegerleme { get; set; }
    }
}
