//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapPlaniCalismaSekli
    {
        public int CalismaSekliKodu { get; set; }
        public string CalismaSekli0 { get; set; }
        public string CalismaSekli1 { get; set; }
        public string CalismaSekli2 { get; set; }
    }
}
