//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPS
    {
        public Nullable<byte> HPSNo { get; set; }
        public string HPSAdi { get; set; }
        public string OzelHesap { get; set; }
        public string Aciklama { get; set; }
        public Nullable<byte> MaxParcaSayisi { get; set; }
    }
}
