//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhracatDosyaFatura
    {
        public string IhracatDosyaNo { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<System.DateTime> FaturaVadesi { get; set; }
        public Nullable<decimal> FaturaTutari { get; set; }
        public string FaturaDovizBirimi { get; set; }
        public Nullable<decimal> Miktar { get; set; }
    }
}
