//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSMalzemeGrubuAltMatrisHSuresi
    {
        public int AltMatrisDegerID { get; set; }
        public int AltMatrisID { get; set; }
        public string Kriter1 { get; set; }
        public string Kriter2 { get; set; }
        public Nullable<int> HazirlikSuresi { get; set; }
    }
}
