//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSMalzemeGrubuStokTurOzelAlan
    {
        public string StokTuru { get; set; }
        public string IPSMalzemeGrubu1Adi { get; set; }
        public string IPSMalzemeGrubu2Adi { get; set; }
        public string IPSMalzemeGrubu3Adi { get; set; }
        public string IPSMalzemeGrubu4Adi { get; set; }
        public string IPSMalzemeGrubu5Adi { get; set; }
        public string IPSMalzemeGrubu6Adi { get; set; }
        public string IPSMalzemeGrubu7Adi { get; set; }
        public string IPSMalzemeGrubu8Adi { get; set; }
        public string IPSMalzemeGrubu9Adi { get; set; }
        public string IPSMalzemeGrubu10Adi { get; set; }
        public string IPSMalzemeGrubu11Adi { get; set; }
        public string IPSMalzemeGrubu12Adi { get; set; }
        public string IPSMalzemeGrubu13Adi { get; set; }
        public string IPSMalzemeGrubu14Adi { get; set; }
        public string IPSMalzemeGrubu15Adi { get; set; }
    }
}
