//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSVeritabani
    {
        public int IPSVeritabaniID { get; set; }
        public string IPSVeritabaniAdi { get; set; }
        public string IPSServerAdi { get; set; }
        public string IPSSifre { get; set; }
        public string IPSKullaniciAdi { get; set; }
    }
}
