//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrsaliyeOdemePlani
    {
        public string IrsaliyeNo { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string DovizBirimi { get; set; }
        public string OdemeTipi { get; set; }
    }
}
