//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemGrupMaliyet
    {
        public string DonemAdi { get; set; }
        public string IslemGrubu { get; set; }
        public string StokTuru { get; set; }
        public string StokGrubu { get; set; }
        public string MaliyetAdi { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string DovizBirimi { get; set; }
        public string HesaplamaTuru { get; set; }
        public string MaliyetOnDeger { get; set; }
        public Nullable<decimal> FireYuzde { get; set; }
    }
}
