//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemGrup
    {
        public string IslemGrubu { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string OzelAlan1 { get; set; }
        public string OzelAlan2 { get; set; }
        public string OzelAlan3 { get; set; }
        public string OzelAlan4 { get; set; }
        public string OzelAlan5 { get; set; }
        public string OzelAlan6 { get; set; }
        public string OzelAlan7 { get; set; }
        public string OzelAlan8 { get; set; }
        public string OzelAlan9 { get; set; }
        public string OzelAlan10 { get; set; }
        public string OzelAlan11 { get; set; }
        public string OzelAlan12 { get; set; }
        public string OzelAlan13 { get; set; }
        public string OzelAlan14 { get; set; }
        public string OzelAlan15 { get; set; }
        public string Aciklama { get; set; }
    }
}
