//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public string IslemNo { get; set; }
        public string IslemAdi { get; set; }
        public string IslemTuru { get; set; }
        public Nullable<decimal> StandartSure { get; set; }
        public Nullable<decimal> UretimHizi { get; set; }
        public string OlcuBirimi { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string DovizBirimi { get; set; }
        public string MakineTuru { get; set; }
        public Nullable<decimal> HazirlikSuresi { get; set; }
        public Nullable<decimal> StandartRandiman { get; set; }
        public Nullable<decimal> FireYuzdesi { get; set; }
        public Nullable<short> BolumAdedi { get; set; }
        public string SarfFisiOlustur { get; set; }
        public string UretimGirisFisiOlustur { get; set; }
        public string IslemYeri { get; set; }
        public Nullable<decimal> CalisanPersonelSayisi { get; set; }
        public string IslemGrubu1 { get; set; }
        public string IslemGrubu2 { get; set; }
        public string IslemGrubu3 { get; set; }
        public string OtomatikMiktarGelsin { get; set; }
        public string MaliyetAnahtari { get; set; }
        public string KaliteOnayi { get; set; }
        public string CokluIsBaslatma { get; set; }
        public string UretimTesti { get; set; }
        public Nullable<decimal> ToleransYuzde { get; set; }
        public Nullable<int> IslemTurTip { get; set; }
        public bool SarimSekliDegistir { get; set; }
        public bool UretimdeKumulatifMtGiris { get; set; }
        public bool SeriNoluMakineMalzemeAtama { get; set; }
        public bool TezgahTipiKontroluYapilsin { get; set; }
        public bool FISTestPeriyot { get; set; }
        public bool MMAtamaOlmadanIslemBaslamasin { get; set; }
        public decimal MMAtamaToleransYuzde { get; set; }
        public Nullable<double> FasonIslemTeminSuresi { get; set; }
        public Nullable<double> FasonIslemMaliyet { get; set; }
        public bool IBSFISDevamOtoSayacSifirla { get; set; }
        public bool IBSFISKKTalimatKabulSifreSorma { get; set; }
    }
}
