//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemTerminAraligi
    {
        public string RefakatNo { get; set; }
        public short SiraNo { get; set; }
        public string IslemGrupAdi { get; set; }
        public string IslemGrupDegeri { get; set; }
        public Nullable<System.DateTime> MinBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> MaxBitisTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
