//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IthalatIhracatEvrakGrubu
    {
        public int EvrakGrubuID { get; set; }
        public string EvrakGrubu { get; set; }
        public short IthalatIhracat { get; set; }
        public string Aciklama { get; set; }
    }
}
