//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karisim
    {
        public string KarisimKodu { get; set; }
        public string KarisimAdi { get; set; }
        public string ElyafTuru1 { get; set; }
        public Nullable<decimal> ElyafYuzde1 { get; set; }
        public string ElyafTuru2 { get; set; }
        public Nullable<decimal> ElyafYuzde2 { get; set; }
        public string ElyafTuru3 { get; set; }
        public Nullable<decimal> ElyafYuzde3 { get; set; }
        public string ElyafTuru4 { get; set; }
        public Nullable<decimal> ElyafYuzde4 { get; set; }
        public string ElyafTuru5 { get; set; }
        public Nullable<decimal> ElyafYuzde5 { get; set; }
        public string ElyafTuru6 { get; set; }
        public Nullable<decimal> ElyafYuzde6 { get; set; }
    }
}
