//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartela
    {
        public int SiraNo { get; set; }
        public string DesenNo { get; set; }
        public string DesenAdi { get; set; }
        public Nullable<decimal> MamulEn { get; set; }
        public Nullable<decimal> MamulGramajm2 { get; set; }
        public string Karisim { get; set; }
        public byte[] YikamaTalimatiResmi { get; set; }
    }
}
