//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaIslemleri
    {
        public int KasaIslemleriID { get; set; }
        public Nullable<int> KasaKartiID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> IslemNo { get; set; }
        public string BelgeNo { get; set; }
        public string IslemTuru { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<double> DovizliTutar { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<double> Kur { get; set; }
        public string IslemAciklamasi { get; set; }
        public Nullable<int> OzelKodlarID { get; set; }
        public string IslemYeri { get; set; }
    }
}
