//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KaynakCalismamaTakvimi
    {
        public int KaynakCalismamaTakvimiID { get; set; }
        public string KaynakGrupTipi { get; set; }
        public string KaynakGrupDegeri { get; set; }
        public Nullable<int> BaslangicGunu { get; set; }
        public string BaslangicZamani { get; set; }
        public Nullable<int> BitisGunu { get; set; }
        public string BitisZamani { get; set; }
        public string CalismamaNedeni { get; set; }
        public Nullable<System.DateTime> GecerlilikBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> GecerlilikBitisTarihi { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
    }
}
