//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KendiCekimiz
    {
        public int KendiCekimizID { get; set; }
        public int BankaHesaplarimID { get; set; }
        public int CekKasasiID { get; set; }
        public string KocanNo { get; set; }
        public string CekSeriNo { get; set; }
        public int CekBaslangicSiraNo { get; set; }
        public int CekAdedi { get; set; }
        public int KullanilanCekAdedi { get; set; }
        public bool Kullanimda { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public System.DateTime DegistirilmeTarihi { get; set; }
        public string DegistirenKullaniciKodu { get; set; }
    }
}
