//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciSQLAnalizGridDuzen
    {
        public string KullaniciKodu { get; set; }
        public int SqlNo { get; set; }
        public string KolonAdi { get; set; }
        public Nullable<int> KolonGenisligi { get; set; }
        public string Islem { get; set; }
        public Nullable<int> Gruplama { get; set; }
        public Nullable<int> KolonSira { get; set; }
    }
}
