//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciListeDuzen
    {
        public string KullaniciKodu { get; set; }
        public string FormAdi { get; set; }
        public string ListeAdi { get; set; }
        public string AlanAdi { get; set; }
        public Nullable<int> Pozisyon { get; set; }
        public Nullable<int> Genislik { get; set; }
        public string Gorunsun { get; set; }
        public string KolonBasligi { get; set; }
    }
}
