//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public string KullaniciKodu { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciTanimi { get; set; }
        public string Sifre { get; set; }
        public string HerGiristeSifreDegisimi { get; set; }
        public string KullaniciSifreDegistiremesin { get; set; }
        public string SifreDegismesin { get; set; }
        public string KullaniciSistemeGiremesin { get; set; }
        public Nullable<short> MaksimumSifreSuresi { get; set; }
        public string BosSifreOlsun { get; set; }
        public Nullable<short> MinimumSifreUzunlugu { get; set; }
        public string SifreHerZamanDegisebilsin { get; set; }
        public Nullable<short> MinimumSifreDegistirmeSuresi { get; set; }
        public string EskiSifreSaklansin { get; set; }
        public Nullable<short> SaklanacakSonSifreSayisi { get; set; }
        public Nullable<short> MaksimumYanlisSifreGirisi { get; set; }
        public Nullable<short> SifreTekrarGirmeSuresi { get; set; }
        public string KilitlemeSistemYoneticiIzni { get; set; }
        public Nullable<short> KilitlemeSuresi { get; set; }
        public string KullaniciGrubu { get; set; }
        public string OnaylayanKullaniciKodu { get; set; }
        public string TeraziMarkasi { get; set; }
        public string DaraTipNo { get; set; }
        public string MailAdresi { get; set; }
        public string ZeminResmiAdresi { get; set; }
        public int VeriYenilemePeriyodu { get; set; }
        public string SiparisFiyatEditEdebilir { get; set; }
        public string HerkeseSiparisGirebilir { get; set; }
        public string SiparisFiyatGorebilir { get; set; }
        public string Renk1 { get; set; }
        public string Renk2 { get; set; }
        public string Renk3 { get; set; }
        public byte KullaniciDil { get; set; }
        public bool SatinalmaFiyatGorebilir { get; set; }
        public bool MakineTakipTumTablariGorsun { get; set; }
        public bool FisTarihiniDegistirebilir { get; set; }
        public bool SiparisOnayYapabilir { get; set; }
        public bool SiparisIptalYapabilir { get; set; }
        public bool SiparisKapatmaYapabilir { get; set; }
        public bool StnSiparisOnayYapabilir { get; set; }
        public bool StnSiparisIptalYapabilir { get; set; }
        public bool StnSiparisKapatmaYapabilir { get; set; }
        public bool StnIstekOnayYapabilir { get; set; }
        public bool StnIstekIptalYapabilir { get; set; }
        public bool StnIstekKapatmaYapabilir { get; set; }
        public string MenuBar { get; set; }
        public bool SiparisFiyatListeOnayYetki { get; set; }
        public bool StnSiparisFiyatListeOnayYetki { get; set; }
        public bool TopluStokGuncellemeYetki { get; set; }
        public bool DokumaDesenMaliyetiniGorebilir { get; set; }
        public bool GantIsYukleriniHareketEttirir { get; set; }
        public bool KTopHataSilmeDegistirmeYetki { get; set; }
        public bool KaynakTakvimdenMTakvimOlustur { get; set; }
        public bool SHKabulMiktarDegistirebilir { get; set; }
        public bool IBSFISKKoduDegistirebilir { get; set; }
        public bool IBSFISDevamOnayiVerebilir { get; set; }
        public bool IBSFISKisitOnayiVerebilir { get; set; }
        public Nullable<int> TeraziPortNo { get; set; }
        public string KullaniciDurumu { get; set; }
        public int KullaniciDurumID { get; set; }
        public bool SifreHatirla { get; set; }
        public bool RezervEdilenTopBolunebilir { get; set; }
        public bool HamKontrolYapabilir { get; set; }
        public bool MamulKontrolYapabilir { get; set; }
        public bool AraKontrolYapabilir { get; set; }
        public int KullaniciId { get; set; }
        public Nullable<int> KullaniciTipi { get; set; }
    }
}
