//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciGrup
    {
        public string KullaniciGrubu { get; set; }
        public string GrupAdi { get; set; }
        public string GrupYetkilisi { get; set; }
        public string HerGiristeSifreDegisimi { get; set; }
        public string KullaniciSifreDegistiremesin { get; set; }
        public string SifreDegismesin { get; set; }
        public string KullaniciSistemeGiremesin { get; set; }
        public string BosSifreOlsun { get; set; }
        public string SifreHerZamanDegisebilsin { get; set; }
        public string EskiSifreSaklansin { get; set; }
        public string KilitlemeSistemYoneticiIzni { get; set; }
        public Nullable<short> MaksimumSifreSuresi { get; set; }
        public Nullable<short> MinimumSifreUzunlugu { get; set; }
        public Nullable<short> MinimumSifreDegistirmeSuresi { get; set; }
        public Nullable<short> SaklanacakSonSifreSayisi { get; set; }
        public Nullable<short> MaksimumYanlisSifreGirisi { get; set; }
        public Nullable<short> SifreTekrarGirmeSuresi { get; set; }
        public Nullable<short> KilitlemeSuresi { get; set; }
    }
}
