//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasTopHataKisitKontrol
    {
        public int KontrolNo { get; set; }
        public string TopNo { get; set; }
        public string HataKodu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<byte> SiraNo { get; set; }
    }
}
