//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasTop
    {
        public string TopNo { get; set; }
        public Nullable<System.DateTime> KontrolTarihi { get; set; }
        public string KontrolVardiyasi { get; set; }
        public string KontrolMakineNo { get; set; }
        public string KontrolPersonelNo { get; set; }
        public Nullable<decimal> BrutMt { get; set; }
        public Nullable<decimal> NetMt { get; set; }
        public Nullable<decimal> BrutKg { get; set; }
        public Nullable<decimal> NetKg { get; set; }
        public Nullable<decimal> IskartaMt { get; set; }
        public Nullable<decimal> IskartaKg { get; set; }
        public Nullable<decimal> DuzeltmeKatsayisi { get; set; }
        public string EtiketNo { get; set; }
        public string DaraTipNo { get; set; }
        public Nullable<short> BantSayisi { get; set; }
        public string TopKKSureDk { get; set; }
        public Nullable<byte> ParcaSayisi { get; set; }
        public Nullable<decimal> TopEni { get; set; }
        public string HamLotNo { get; set; }
        public string Sevk { get; set; }
        public Nullable<decimal> HamGirisMt { get; set; }
        public string Kombin { get; set; }
        public string AmbalajTipNo { get; set; }
        public string KaliteOnayi { get; set; }
        public string Aciklama { get; set; }
        public string KaliteKodu { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<short> SiparisSiraNo { get; set; }
        public string PartiNo { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> Gramaj { get; set; }
        public string GeldigiCariNo { get; set; }
        public string SonrakiIslemYeri { get; set; }
        public string MusteriCariNo { get; set; }
        public Nullable<short> OncelikNo { get; set; }
        public string MamulLotNo { get; set; }
        public Nullable<decimal> MamulGirisMt { get; set; }
        public string HamTopNo { get; set; }
        public string SayacKodu { get; set; }
        public Nullable<int> KayitSiraNo { get; set; }
        public string HamMamul { get; set; }
        public string UretimMakineNo { get; set; }
        public string AmbarNo { get; set; }
        public string AmbalajNo { get; set; }
        public Nullable<byte> HataPuanSistemNo { get; set; }
        public string TopKesimSaati { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public string Tebdil { get; set; }
        public Nullable<decimal> ToplamHataPuani { get; set; }
        public string EsTopNo { get; set; }
        public Nullable<decimal> IskontoMt { get; set; }
        public string KKLotNo { get; set; }
        public string TopBaslamaSaati { get; set; }
        public string TopBitisTarihi { get; set; }
        public string TopKesenPersonelNo { get; set; }
        public string IcSevk { get; set; }
        public string BirlesmisTopNo { get; set; }
        public Nullable<decimal> NetAdet { get; set; }
        public string TopDurumu { get; set; }
        public Nullable<byte> IslemTipi { get; set; }
        public bool StokHareketGirisiYapildi { get; set; }
        public string TopBolmeNedeni { get; set; }
        public string KaliteNedeni { get; set; }
        public Nullable<System.DateTime> KaliteKoduDegistirmeTarihi { get; set; }
        public string KaliteKoduDegistirenKullanici { get; set; }
        public string TopBolunenMakineNo { get; set; }
        public Nullable<System.DateTime> TopBolmeBaslamaTarihiSaati { get; set; }
        public Nullable<System.DateTime> TopBolmeBitisTarihiSaati { get; set; }
        public Nullable<int> IslemSiraNo { get; set; }
        public string DisBarkodNo { get; set; }
    }
}
