//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasTopOzelAlanDeger
    {
        public string TopNo { get; set; }
        public int SiraNo { get; set; }
        public Nullable<decimal> NetMt { get; set; }
        public string KumasTopOzelAlan1Deger { get; set; }
        public string KumasTopOzelAlan2Deger { get; set; }
        public string KumasTopOzelAlan3Deger { get; set; }
        public string KumasTopOzelAlan4Deger { get; set; }
        public string KumasTopOzelAlan5Deger { get; set; }
        public string KumasTopOzelAlan6Deger { get; set; }
        public string KumasTopOzelAlan7Deger { get; set; }
        public string KumasTopOzelAlan8Deger { get; set; }
        public string KumasTopOzelAlan9Deger { get; set; }
        public string KumasTopOzelAlan10Deger { get; set; }
        public string KumasTopOzelAlan11Deger { get; set; }
        public string KumasTopOzelAlan12Deger { get; set; }
        public string KumasTopOzelAlan13Deger { get; set; }
        public string KumasTopOzelAlan14Deger { get; set; }
        public string KumasTopOzelAlan15Deger { get; set; }
    }
}
