//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasTopIskarta
    {
        public int KumasTopIskartaID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string RefakatNo { get; set; }
        public Nullable<int> IslemSiraNo { get; set; }
        public Nullable<double> NetMt { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string MakineNo { get; set; }
        public string PersonelNo { get; set; }
        public string TopNo { get; set; }
        public string EtiketNo { get; set; }
        public string KaliteKodu { get; set; }
    }
}
