//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasTakipKarti
    {
        public string KazanNo { get; set; }
        public string SiparisNo { get; set; }
        public string MusteriCariNo { get; set; }
        public string DokumaDesenNo { get; set; }
        public string RenkKodu { get; set; }
        public string Islem { get; set; }
        public string HamLotNo { get; set; }
        public Nullable<decimal> MamulEn { get; set; }
        public Nullable<int> KartNo { get; set; }
        public Nullable<short> KazanSiraNo { get; set; }
        public string UretimMakineNo { get; set; }
        public Nullable<decimal> HamGirisMt { get; set; }
        public Nullable<decimal> HamGirisKg { get; set; }
        public string StokKodu { get; set; }
        public string SonrakiIslemYeri { get; set; }
        public string Tebdil { get; set; }
        public string GeldigiCariNo { get; set; }
    }
}
