//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakineLayout
    {
        public string KullaniciKodu { get; set; }
        public string MakineNo { get; set; }
        public string MakineAdi { get; set; }
        public string MakineTuru { get; set; }
        public Nullable<byte> OtomasyonDurumu { get; set; }
        public Nullable<byte> SatirSayisi { get; set; }
        public Nullable<int> SolKenar { get; set; }
        public Nullable<int> UstKenar { get; set; }
        public Nullable<int> Yukseklik { get; set; }
        public Nullable<int> Genislik { get; set; }
        public string Tipi { get; set; }
        public string NesneAdi { get; set; }
    }
}
