//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakineMalzemeAtama
    {
        public int SiraNo { get; set; }
        public string MakineNo { get; set; }
        public System.DateTime AtamaTarihi { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<decimal> BaslamaMiktari { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string RefakatKartNo { get; set; }
        public Nullable<short> IslemSiraNo { get; set; }
        public Nullable<short> UrunAgaciSiraNo { get; set; }
        public decimal IlkAtamaMiktari { get; set; }
        public string Aciklama { get; set; }
        public int UrunAgaciAlternatifNo { get; set; }
        public string AtamaYapilanAmbarNo { get; set; }
    }
}
