//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakineTur
    {
        public string MakineTuru { get; set; }
        public string MakineTurAdi { get; set; }
        public string PrgZamanKisiti { get; set; }
        public byte[] Resim { get; set; }
        public string OzelAlan1Adi { get; set; }
        public string OzelAlan2Adi { get; set; }
        public string OzelAlan3Adi { get; set; }
        public string OzelAlan4Adi { get; set; }
        public string OzelAlan5Adi { get; set; }
        public string OzelAlan6Adi { get; set; }
        public string OzelAlan7Adi { get; set; }
        public string OzelAlan8Adi { get; set; }
        public string OzelAlan9Adi { get; set; }
        public string OzelAlan10Adi { get; set; }
        public string OzelAlan11Adi { get; set; }
        public string OzelAlan12Adi { get; set; }
        public string OzelAlan13Adi { get; set; }
        public string OzelAlan14Adi { get; set; }
        public string OzelAlan15Adi { get; set; }
        public string MakineGrubu { get; set; }
        public int RandimanKriter1 { get; set; }
        public int RandimanKriter2 { get; set; }
        public string RandimanRenk1 { get; set; }
        public string RandimanRenk2 { get; set; }
        public string RandimanRenk3 { get; set; }
        public string OzelAlan1DosyaAdi { get; set; }
        public string OzelAlan2DosyaAdi { get; set; }
        public string OzelAlan3DosyaAdi { get; set; }
        public string OzelAlan4DosyaAdi { get; set; }
        public string OzelAlan5DosyaAdi { get; set; }
        public string OzelAlan6DosyaAdi { get; set; }
        public string OzelAlan7DosyaAdi { get; set; }
        public string OzelAlan8DosyaAdi { get; set; }
        public string OzelAlan9DosyaAdi { get; set; }
        public string OzelAlan10DosyaAdi { get; set; }
        public string OzelAlan11DosyaAdi { get; set; }
        public string OzelAlan12DosyaAdi { get; set; }
        public string OzelAlan13DosyaAdi { get; set; }
        public string OzelAlan14DosyaAdi { get; set; }
        public string OzelAlan15DosyaAdi { get; set; }
        public string OzelAlan1DosyaAlanAdi { get; set; }
        public string OzelAlan2DosyaAlanAdi { get; set; }
        public string OzelAlan3DosyaAlanAdi { get; set; }
        public string OzelAlan4DosyaAlanAdi { get; set; }
        public string OzelAlan5DosyaAlanAdi { get; set; }
        public string OzelAlan6DosyaAlanAdi { get; set; }
        public string OzelAlan7DosyaAlanAdi { get; set; }
        public string OzelAlan8DosyaAlanAdi { get; set; }
        public string OzelAlan9DosyaAlanAdi { get; set; }
        public string OzelAlan10DosyaAlanAdi { get; set; }
        public string OzelAlan11DosyaAlanAdi { get; set; }
        public string OzelAlan12DosyaAlanAdi { get; set; }
        public string OzelAlan13DosyaAlanAdi { get; set; }
        public string OzelAlan14DosyaAlanAdi { get; set; }
        public string OzelAlan15DosyaAlanAdi { get; set; }
    }
}
