//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetHesapDonemTutar
    {
        public string MaliyetDonemi { get; set; }
        public string MaliyetAdi { get; set; }
        public string MaliyetMerkezNo { get; set; }
        public string HesapKodu { get; set; }
        public Nullable<decimal> GerceklesenTutar { get; set; }
        public Nullable<decimal> TahminiTutar { get; set; }
    }
}
