//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetDonemUretim
    {
        public string DonemAdi { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> UretimMiktari { get; set; }
        public Nullable<decimal> AmbalajliUretimMiktari { get; set; }
        public Nullable<decimal> CalisilanVardiyaSayisi { get; set; }
        public Nullable<decimal> VardiyaCalismaSaati { get; set; }
        public Nullable<decimal> ElektrikTuketimKw { get; set; }
    }
}
