//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetDonemStok
    {
        public string DonemAdi { get; set; }
        public string StokKodu { get; set; }
        public decimal Miktar1 { get; set; }
        public decimal Miktar2 { get; set; }
        public decimal Miktar3 { get; set; }
        public decimal AOMFiyat { get; set; }
        public decimal FIFOFiyat { get; set; }
        public decimal LIFOFiyat { get; set; }
        public decimal SonDegerFiyat { get; set; }
        public string DovizBirimi { get; set; }
        public int KayitSayisi { get; set; }
    }
}
