//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManuelRefakatKarti
    {
        public string RefakatKartNo { get; set; }
        public System.DateTime DuzenlemeTarihi { get; set; }
        public string SiparisNo { get; set; }
        public string MusteriCariNo { get; set; }
        public string DokumaDesenNo { get; set; }
        public string RenkKodu { get; set; }
        public string BaskiDesenVaryantNo { get; set; }
        public string Islem { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public string Numune { get; set; }
        public string BaskiAlti { get; set; }
        public Nullable<decimal> HamEn { get; set; }
        public Nullable<decimal> MamulEn { get; set; }
        public Nullable<decimal> IstenenEn { get; set; }
        public Nullable<decimal> IstenenGramajmt { get; set; }
        public Nullable<decimal> IstenenGramajm2 { get; set; }
        public Nullable<decimal> HamGirisMt { get; set; }
        public Nullable<decimal> HamGirisKg { get; set; }
        public Nullable<short> HamGirisAdet { get; set; }
        public Nullable<decimal> MamulCikisMt { get; set; }
        public Nullable<decimal> MamulCikisKg { get; set; }
        public string Aciklama { get; set; }
        public string KazanNo { get; set; }
        public string CalismaSekli { get; set; }
        public string GeldigiCariNo { get; set; }
        public string ReferansMusteri { get; set; }
        public string BaskiCinsi { get; set; }
        public string RefakatKartiTipi { get; set; }
        public Nullable<decimal> BasilacakKumasMt { get; set; }
        public Nullable<decimal> BasilacakKumasKg { get; set; }
    }
}
