//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulProgram
    {
        public int ModulProgramNo { get; set; }
        public string ModulProgramAdi { get; set; }
        public Nullable<System.DateTime> SistemeGirisTarihi { get; set; }
        public string Satildi { get; set; }
        public string KullaniciSayisi { get; set; }
        public Nullable<int> TanimFormID { get; set; }
        public int TanimTip { get; set; }
    }
}
