//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRPEksi
    {
        public string SiparisNo { get; set; }
        public int SiraNo { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public System.DateTime RaporTarihi { get; set; }
        public string Neden { get; set; }
    }
}
