//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mrv_POY_Ikaz
    {
        public int ID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string PartiNo { get; set; }
        public string Denye_Flaman { get; set; }
        public string Uretim_Mak_Kan_Poz { get; set; }
        public string ProblemTanimi { get; set; }
        public string YapilanMudahale { get; set; }
        public string Teksture_Makine_No { get; set; }
        public Nullable<int> Teksture_Pozisyon_No { get; set; }
        public Nullable<System.DateTime> LabIncelemeTarihi { get; set; }
        public string LabSonuc { get; set; }
        public string TekstureSonuc { get; set; }
        public string SiraliYuklemeIstekTalebi { get; set; }
        public Nullable<System.DateTime> UretimMudahaleTarih { get; set; }
        public string TekstureKullanici { get; set; }
        public string UretimKullanici { get; set; }
        public string LabKullanici { get; set; }
    }
}
