//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mrv_KaliteBildirim_Makine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mrv_KaliteBildirim_Makine()
        {
            this.Mrv_KaliteBildirimDetay = new HashSet<Mrv_KaliteBildirimDetay>();
        }
    
        public int ID { get; set; }
        public string MakineAdi { get; set; }
        public Nullable<int> Isletme { get; set; }
    
        public virtual Mrv_KaliteBildirimBolumleri Mrv_KaliteBildirimBolumleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mrv_KaliteBildirimDetay> Mrv_KaliteBildirimDetay { get; set; }
    }
}
