//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mrv_KaliteBildirimHata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mrv_KaliteBildirimHata()
        {
            this.Mrv_KaliteBildirimHataMudahale = new HashSet<Mrv_KaliteBildirimHataMudahale>();
            this.Mrv_KaliteBildirimDetay = new HashSet<Mrv_KaliteBildirimDetay>();
            this.Mrv_KaliteBildirimDetay1 = new HashSet<Mrv_KaliteBildirimDetay>();
            this.Mrv_KaliteBildirimDetay2 = new HashSet<Mrv_KaliteBildirimDetay>();
        }
    
        public int ID { get; set; }
        public string Bolum { get; set; }
        public string HataTanimi { get; set; }
        public Nullable<int> BolumNo { get; set; }
        public Nullable<int> MudahaleId { get; set; }
    
        public virtual Mrv_KaliteBildirimBolumleri Mrv_KaliteBildirimBolumleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mrv_KaliteBildirimHataMudahale> Mrv_KaliteBildirimHataMudahale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mrv_KaliteBildirimDetay> Mrv_KaliteBildirimDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mrv_KaliteBildirimDetay> Mrv_KaliteBildirimDetay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mrv_KaliteBildirimDetay> Mrv_KaliteBildirimDetay2 { get; set; }
    }
}
