//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTGridDil
    {
        public string AlanAdi { get; set; }
        public int SiraNo { get; set; }
        public string Baslik0 { get; set; }
        public string Baslik1 { get; set; }
        public string Baslik2 { get; set; }
        public string Baslik3 { get; set; }
        public string Baslik4 { get; set; }
        public string Baslik5 { get; set; }
        public string Baslik6 { get; set; }
        public string Baslik7 { get; set; }
        public string Baslik8 { get; set; }
        public string Baslik9 { get; set; }
    }
}
