//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MudaheleNedeni
    {
        public string MudaheleNo { get; set; }
        public string MudaheleAdi { get; set; }
        public bool OtomasyondaKullaniliyorMu { get; set; }
        public string OtomasyonMudaheleNo { get; set; }
    }
}
