//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuhasebeHesapDonem
    {
        public string MuhasebeHesapDonemi { get; set; }
        public System.DateTime DonemBaslangicTarihi { get; set; }
        public System.DateTime DonemBitisTarihi { get; set; }
        public string DonemiKapatanPersonelNo { get; set; }
        public Nullable<System.DateTime> DonemKapatmaTarihi { get; set; }
    }
}
