//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuhasebeFisi
    {
        public int MuhasebeFisiID { get; set; }
        public Nullable<int> MuhasebeFisiAnaID { get; set; }
        public Nullable<int> HesapPlaniID { get; set; }
        public string BorcAlacak { get; set; }
        public Nullable<double> YerelTutar { get; set; }
        public Nullable<double> DovizliTutar { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<double> Kur { get; set; }
        public string Aciklama { get; set; }
        public Nullable<double> Miktar { get; set; }
    }
}
