//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuhasebeEntegrasyon
    {
        public int MuhasebeEntegrasyonID { get; set; }
        public int IslemID { get; set; }
        public string IslemYeri { get; set; }
        public Nullable<int> HesapPlaniID { get; set; }
        public string BorcAlacak { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> EntegrasyonTarihi { get; set; }
        public string EntegrasyonuYapan { get; set; }
        public Nullable<int> MuhasebeFisiID { get; set; }
    }
}
