//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationButton
    {
        public int NavigationID { get; set; }
        public int BarID { get; set; }
        public string Kullanicikodu { get; set; }
        public string ButtonCaption { get; set; }
        public Nullable<int> ButtonIndex { get; set; }
        public Nullable<int> ButtonImgIndex { get; set; }
        public Nullable<int> ButtonSira { get; set; }
    }
}
