//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumuneDokumaDesen
    {
        public string NumuneDesenNo { get; set; }
        public string DesenAdi { get; set; }
        public string OrguTipi { get; set; }
        public string KumasCinsi { get; set; }
        public Nullable<decimal> HamEn { get; set; }
        public Nullable<decimal> HamGramajm2 { get; set; }
        public string Karisim { get; set; }
        public Nullable<decimal> MamulEn { get; set; }
        public Nullable<decimal> MamulGramajm2 { get; set; }
        public string DesenResimAdresi { get; set; }
        public string CozguRaporu1 { get; set; }
        public Nullable<decimal> TarakEni { get; set; }
        public Nullable<decimal> TarakNo { get; set; }
        public Nullable<short> ToplamTelAdedi { get; set; }
        public Nullable<byte> UretimBantAdedi { get; set; }
        public Nullable<decimal> BantGenisligi { get; set; }
        public Nullable<decimal> CozguBuzulmeYuzdesi { get; set; }
        public Nullable<decimal> AtkiBuzulmeYuzdesi { get; set; }
        public Nullable<decimal> KenarEni { get; set; }
        public string AtkiRaporu { get; set; }
        public Nullable<decimal> OrtalamaSiklik { get; set; }
        public string YikamaTalimatiResimAdresi { get; set; }
        public string SayacKodu { get; set; }
        public Nullable<int> KayitSiraNo { get; set; }
    }
}
