//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnMaliyetUrunAgaci
    {
        public int OnMaliyetSiraNo { get; set; }
        public byte SiraNo { get; set; }
        public string BilesenStokKodu { get; set; }
        public Nullable<decimal> KullanimMiktari { get; set; }
        public Nullable<decimal> FireYuzde { get; set; }
        public Nullable<decimal> En { get; set; }
        public Nullable<decimal> Boy { get; set; }
        public Nullable<System.DateTime> BaslangicGecerlilikTarihi { get; set; }
        public Nullable<System.DateTime> BitisGecerlilikTarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<decimal> Kur { get; set; }
    
        public virtual OlcuBirim OlcuBirim { get; set; }
    }
}
