//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtomatikStokKodAd
    {
        public string StokTuru { get; set; }
        public byte SiraNo { get; set; }
        public string KodStokAlani { get; set; }
        public string AdStokAlani { get; set; }
        public string KodSabitBilgi { get; set; }
        public string AdSabitBilgi { get; set; }
        public Nullable<byte> KodBaslangicKarakterNo { get; set; }
        public Nullable<byte> KodKullanilanKarakterSayisi { get; set; }
        public string KodAyiracKarakter { get; set; }
        public Nullable<byte> AdBaslangicKarakterNo { get; set; }
        public Nullable<byte> AdKullanilanKarakterSayisi { get; set; }
        public string AdAyiracKarakter { get; set; }
        public string KodSayac { get; set; }
        public string KodZorunluBilgi { get; set; }
        public string AdZorunluBilgi { get; set; }
        public string TicariKodStokAlani { get; set; }
        public string TicariAdStokAlani { get; set; }
        public string TicariKodSabitBilgi { get; set; }
        public string TicariAdSabitBilgi { get; set; }
        public Nullable<byte> TicariKodBaslangicKarakterNo { get; set; }
        public Nullable<byte> TicariKodKulKarakterSayisi { get; set; }
        public string TicariKodAyiracKarakter { get; set; }
        public Nullable<byte> TicariAdBaslangicKarakterNo { get; set; }
        public Nullable<byte> TicariAdKulKarakterSayisi { get; set; }
        public string TicariAdAyiracKarakter { get; set; }
        public string TicariKodSayac { get; set; }
        public string StokKodunaGiriyor { get; set; }
        public bool GrupluSayacVar { get; set; }
        public bool SayacKoy { get; set; }
        public bool GrupluOzelSayacVar { get; set; }
    }
}
