//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtoUretimMakineParametre
    {
        public int ParametreNo { get; set; }
        public string MakineTuru { get; set; }
        public string ParametreAdi { get; set; }
        public string VeriTipi { get; set; }
        public int VeriBoyutu { get; set; }
        public byte VeriOndalikSayisi { get; set; }
        public string Aciklama { get; set; }
    }
}
