//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartilenmemisSiparisIhtiyac
    {
        public System.DateTime RaporTarihi { get; set; }
        public string SiparisNo { get; set; }
        public int SiparisSiraNo { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> IhtiyacMiktar1 { get; set; }
        public string OlcuBirimi1 { get; set; }
        public Nullable<decimal> IhtiyacMiktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<decimal> RezervMiktari { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
    }
}
