//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCSonKullanici
    {
        public string PCAdi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
    }
}
