//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelKazancKesintiBilgileri
    {
        public string IsyeriKodu { get; set; }
        public string PersonelNo { get; set; }
        public int Yil { get; set; }
        public int Ay { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<double> BrutUcret { get; set; }
        public Nullable<double> Ek { get; set; }
        public Nullable<double> Yardim { get; set; }
        public Nullable<double> KazancToplam { get; set; }
        public Nullable<double> IsciSsk { get; set; }
        public Nullable<double> IsverenSsk { get; set; }
        public Nullable<double> IsciIssizlik { get; set; }
        public Nullable<double> IsverenIssizlik { get; set; }
        public Nullable<double> GelirVergiMatrahi { get; set; }
        public Nullable<double> GelirVergisi { get; set; }
        public Nullable<double> DamgaVergisi { get; set; }
        public Nullable<double> KesintiToplam { get; set; }
        public Nullable<double> Yuvarlama { get; set; }
        public Nullable<double> Yol { get; set; }
        public Nullable<double> AileCocuk { get; set; }
        public Nullable<double> Yemek { get; set; }
        public Nullable<double> NetOdenen { get; set; }
        public Nullable<double> NormalGun { get; set; }
        public Nullable<double> HaftalikTatil { get; set; }
        public Nullable<double> GenelTatil { get; set; }
        public Nullable<double> ToplamGun { get; set; }
        public Nullable<double> OzelIndirim { get; set; }
    }
}
