//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGorevTakip
    {
        public int PersonelGorevTakipID { get; set; }
        public string PersonelNo { get; set; }
        public string Gorev { get; set; }
        public Nullable<System.DateTime> Zaman { get; set; }
    }
}
