//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelPuantaj
    {
        public string IsyeriKodu { get; set; }
        public string PersonelNo { get; set; }
        public string BordroKalemTuru { get; set; }
        public string BordroKalemAdi { get; set; }
        public Nullable<double> Ucret { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<double> GunlukSaat { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<double> ToplamKazanc { get; set; }
        public Nullable<double> ToplamYardim { get; set; }
        public Nullable<double> ToplamKesinti { get; set; }
    }
}
