//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSQLAlanlariParametre
    {
        public int ProgramSQLAlanlariParametreID { get; set; }
        public Nullable<int> ProgramSQLleriID { get; set; }
        public string ParametreAdi { get; set; }
        public string ParametreTipi { get; set; }
        public Nullable<int> KontrolID { get; set; }
    }
}
