//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeTuruPersonel
    {
        public int ProjeTuruPersonelID { get; set; }
        public Nullable<int> ProjeTuruID { get; set; }
        public string YetkiliPersonelNo { get; set; }
        public string ProjeSorumlusumu { get; set; }
    }
}
