//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeEkleri
    {
        public int ProjeEkleriID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public string EkReferans { get; set; }
        public Nullable<int> EkReferansID { get; set; }
        public Nullable<int> ProjeEkTuruID { get; set; }
        public string EkKonusu { get; set; }
        public string EkAciklama { get; set; }
        public string EkLink { get; set; }
        public Nullable<System.DateTime> EkTarihi { get; set; }
        public string EkVersiyon { get; set; }
        public string AktifPasif { get; set; }
    }
}
