//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeAdimOncelik
    {
        public int ProjeAdimOncelikID { get; set; }
        public Nullable<int> ProjeAdimlariID { get; set; }
        public Nullable<int> BagliProjeAdimiID { get; set; }
        public string Oncelik { get; set; }
        public string AktifPasif { get; set; }
    }
}
