//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeDurus
    {
        public int ProjeDurusID { get; set; }
        public Nullable<int> ProjeAdimlariID { get; set; }
        public Nullable<int> ProjeAdimlariDurumuID { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<int> ProjeDurusNedenID { get; set; }
        public Nullable<System.DateTime> DurusBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> DurusBitisTarihi { get; set; }
        public string DurusAciklama { get; set; }
        public string AktifPasif { get; set; }
        public Nullable<int> MesajID { get; set; }
    }
}
