//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceteOzelAlanDeger
    {
        public string ReceteNo { get; set; }
        public string OzelAlan1Deger { get; set; }
        public string OzelAlan2Deger { get; set; }
        public string OzelAlan3Deger { get; set; }
        public string OzelAlan4Deger { get; set; }
        public string OzelAlan5Deger { get; set; }
        public string OzelAlan6Deger { get; set; }
        public string OzelAlan7Deger { get; set; }
        public string OzelAlan8Deger { get; set; }
        public string OzelAlan9Deger { get; set; }
        public string OzelAlan10Deger { get; set; }
        public string OzelAlan11Deger { get; set; }
        public string OzelAlan12Deger { get; set; }
        public string OzelAlan13Deger { get; set; }
        public string OzelAlan14Deger { get; set; }
        public string OzelAlan15Deger { get; set; }
    }
}
