//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        public string ReceteNo { get; set; }
        public short SiraNo { get; set; }
        public Nullable<short> ReceteSiraNo { get; set; }
        public string SafhaAdi { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> BirimKullanimMiktari { get; set; }
        public string OlcuBirimi { get; set; }
        public string Aciklama { get; set; }
        public string BanyoDegisimi { get; set; }
        public string AlternatifStokKodu { get; set; }
        public string AlternatifLotNo { get; set; }
        public string AmbarNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public string OB1 { get; set; }
        public string Aciklama2 { get; set; }
        public Nullable<decimal> ReceteKonsantrasyonu { get; set; }
        public string Durumu { get; set; }
        public string TeraziAdi { get; set; }
        public string SablonNo { get; set; }
        public Nullable<double> Tolerans { get; set; }
    }
}
