//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefakatKarti
    {
        public string RefakatNo { get; set; }
        public short IslemSiraNo { get; set; }
        public string IslemNo { get; set; }
        public string PartiBirlestirme { get; set; }
        public Nullable<System.DateTime> ProgramTarihi { get; set; }
        public string MakineNo { get; set; }
        public string ReceteNo { get; set; }
        public string IslemTipi { get; set; }
        public Nullable<System.DateTime> IslemBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> IslemBitisTarihi { get; set; }
        public string IslemSonucu { get; set; }
        public string IslemDurumu { get; set; }
        public Nullable<decimal> StandartSure { get; set; }
        public Nullable<decimal> UretimHizi { get; set; }
        public string OlcuBirimi { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public string OlcuBirimi1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<decimal> HazirlikSuresi { get; set; }
        public Nullable<decimal> StandartRandiman { get; set; }
        public Nullable<decimal> FireYuzdesi { get; set; }
        public string SarjNo { get; set; }
        public Nullable<short> CalisanBolumAdedi { get; set; }
        public string SarfFisiOlustur { get; set; }
        public string UretimGirisFisiOlustur { get; set; }
        public string Talimat { get; set; }
        public string UretimGirisAmbarNo { get; set; }
        public string CikanStokKodu { get; set; }
        public string Aciklama { get; set; }
        public string UretimCikisAmbarNo { get; set; }
        public Nullable<decimal> CalisanPersonelSayisi { get; set; }
        public string EkIslemNedeni { get; set; }
        public string IsYukuRenk { get; set; }
        public string KaliteOnayi { get; set; }
        public string HataliAmbarNo { get; set; }
        public decimal KuyrukSuresi { get; set; }
        public Nullable<decimal> CalisilmayanSure { get; set; }
        public Nullable<decimal> Miktar3 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public Nullable<System.DateTime> IlkProgramTarihi { get; set; }
        public Nullable<System.DateTime> SonRevizyonTarihi { get; set; }
        public Nullable<decimal> CozeltiMiktari { get; set; }
        public bool MiktarSabitKalsin { get; set; }
        public int RefakatKartiBarkodu { get; set; }
        public Nullable<decimal> CozeltiMiktari2 { get; set; }
        public string GrupNo { get; set; }
        public byte GrupSiraNo { get; set; }
        public bool MakineSabitleme { get; set; }
        public string SabitlenenMakineNo { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public Nullable<System.DateTime> TanimlandigiTarih { get; set; }
        public int GrupUstSiraNo { get; set; }
        public short KesilenIslemSiraNo { get; set; }
        public Nullable<bool> IsletmeIslemSabitleme { get; set; }
    }
}
