//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefakatOncelik
    {
        public string PartiNo { get; set; }
        public string MakineNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> OncelikSiraNo { get; set; }
        public Nullable<System.DateTime> ProgramTarihi { get; set; }
        public Nullable<int> ReferansNo { get; set; }
        public string Aciklama { get; set; }
    }
}
