//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefakatKartiOtoYedek
    {
        public string RefakatNo { get; set; }
        public short IslemSiraNo { get; set; }
        public Nullable<System.DateTime> ProgramTarihi { get; set; }
        public Nullable<System.DateTime> IslemBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> IslemBitisTarihi { get; set; }
        public Nullable<decimal> StandartSure { get; set; }
        public Nullable<decimal> HazirlikSuresi { get; set; }
        public Nullable<decimal> UretimHizi { get; set; }
        public Nullable<decimal> StandartRandiman { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public Nullable<decimal> CalisilmayanSure { get; set; }
        public string CikanStokKodu { get; set; }
        public string IsYukuRenk { get; set; }
        public string MakineNo { get; set; }
        public string IslemDurumu { get; set; }
        public Nullable<System.DateTime> TahminiIslemBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> TahminiIslemBitisTarihi { get; set; }
        public Nullable<System.DateTime> SonRevizyonTarihi { get; set; }
    }
}
