//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SabitKiymetAmortisman
    {
        public int SabitKiymetAmortismanID { get; set; }
        public string SabitKiymetKodu { get; set; }
        public int Yil { get; set; }
        public int Ay { get; set; }
        public double AmortismanKarsilikHesapTutari { get; set; }
        public double GiderHesapTutari { get; set; }
        public double CalismayanGiderHesapTutari { get; set; }
        public Nullable<double> KiralikAmortismanHesapTutari { get; set; }
        public double BirikmisAmortismanHesapTutari { get; set; }
        public Nullable<int> FinansHareketAnaID { get; set; }
    }
}
