//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SablonGostergeAyrinti
    {
        public string KullaniciKodu { get; set; }
        public string NesneAdi { get; set; }
        public string AlanAdi { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string Icerik { get; set; }
        public string HucreRengi { get; set; }
        public string YaziTipi { get; set; }
        public byte YaziBuyuklugu { get; set; }
        public string YaziRengi { get; set; }
        public bool Bold { get; set; }
        public byte Hizalama { get; set; }
        public byte SatirYuksekligi { get; set; }
    }
}
