//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SablonGosterge
    {
        public string KullaniciKodu { get; set; }
        public string NesneAdi { get; set; }
        public string GostergeAdi { get; set; }
        public string GostergeSQL { get; set; }
        public int Kolon1Genislik { get; set; }
        public int Kolon2Genislik { get; set; }
    }
}
