//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaIstekTurOzelAlanlari
    {
        public string SatinalmaIstekTuru { get; set; }
        public string OzelAlan1Adi { get; set; }
        public string OzelAlan2Adi { get; set; }
        public string OzelAlan3Adi { get; set; }
        public string OzelAlan4Adi { get; set; }
        public string OzelAlan5Adi { get; set; }
        public string OzelAlan6Adi { get; set; }
        public string OzelAlan7Adi { get; set; }
        public string OzelAlan8Adi { get; set; }
        public string OzelAlan9Adi { get; set; }
        public string OzelAlan10Adi { get; set; }
    }
}
