//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaSozlesmeAna
    {
        public string SozlesmeNo { get; set; }
        public Nullable<System.DateTime> SozlesmeTarihi { get; set; }
        public string CariNo { get; set; }
        public string YetkiliKisiler { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Onay { get; set; }
    }
}
