//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaProformaFaturaAna
    {
        public int ProformaFaturaNo { get; set; }
        public string BelgeNo { get; set; }
        public System.DateTime ProformaTarihi { get; set; }
        public string Duzenleyen { get; set; }
        public string CariNo { get; set; }
        public string BizimBanka { get; set; }
        public string BizimBankaSubesi { get; set; }
        public string BizimHesapNo { get; set; }
        public string MusteriBankasi { get; set; }
        public string MusteriBankaSubesi { get; set; }
        public string MusteriHesapNo { get; set; }
        public string AmbalajTipi { get; set; }
        public string OdemeSekli { get; set; }
        public string TeslimSekli { get; set; }
        public string NakliyeSekli { get; set; }
        public string NakliyeFirmasi { get; set; }
        public Nullable<decimal> SevkiyatToleransi { get; set; }
        public Nullable<System.DateTime> SonYuklemeTarihi { get; set; }
        public string KismiSevkiyat { get; set; }
        public string Aciklama { get; set; }
        public string CariAdres { get; set; }
        public string PaketlemeSekli { get; set; }
    }
}
