//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisFiyatTalep
    {
        public int TalepNo { get; set; }
        public string StokKodu { get; set; }
        public string CariNo { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<double> SiparisMiktari { get; set; }
        public Nullable<double> HedefSatisMiktari { get; set; }
        public Nullable<double> ListeFiyati { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<short> SiraNo { get; set; }
    }
}
