//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaFiyatListeMiktarFiyatIliskisi
    {
        public string SatinalmaFiyatListeNo { get; set; }
        public short SatinalmaFiyatListeSiraNo { get; set; }
        public short SiraNo { get; set; }
        public decimal MiktarBaslangic { get; set; }
        public decimal MiktarBitis { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<decimal> Fiyat2 { get; set; }
        public string DovizBirimi2 { get; set; }
        public Nullable<decimal> Fiyat3 { get; set; }
        public string DovizBirimi3 { get; set; }
        public string Aciklama { get; set; }
    }
}
