//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaSevkiyatPlani
    {
        public string SatinalmaSiparisNo { get; set; }
        public short SatinalmaSiparisSiraNo { get; set; }
        public short SiraNo { get; set; }
        public Nullable<System.DateTime> PlanlananSevkTarihi { get; set; }
        public Nullable<decimal> SevkMiktari { get; set; }
        public string SevkYeri { get; set; }
        public string NakliyeSekli { get; set; }
        public string TeslimSekli { get; set; }
        public string Aciklama { get; set; }
    }
}
