//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaIstek
    {
        public string SatinalmaIstekNo { get; set; }
        public byte SiraNo { get; set; }
        public string StokTuru { get; set; }
        public string StokKodu { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public string OlcuBirimi { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public Nullable<decimal> TahminiFiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string Aciklama { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public string Kapatan { get; set; }
        public Nullable<System.DateTime> KapatmaTarihi { get; set; }
        public string IptalEden { get; set; }
        public Nullable<System.DateTime> IptalTarihi { get; set; }
        public string SatinalmaSiparisNo { get; set; }
        public Nullable<byte> SatinalmaSiparisSiraNo { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<byte> SiparisSiraNo { get; set; }
        public Nullable<decimal> ToleransYuzde { get; set; }
        public string IptalNedeni { get; set; }
        public string IstekDurumu { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<decimal> Miktar3 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public string CariNo { get; set; }
    }
}
