//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaSiparisAna
    {
        public string SatinalmaSiparisNo { get; set; }
        public System.DateTime VerilmeTarihi { get; set; }
        public string CariNo { get; set; }
        public string SiparisTuru { get; set; }
        public string Aciklama { get; set; }
        public string BelgeNo { get; set; }
        public string Duzenleyen { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public Nullable<System.DateTime> TedarikciOnayTarihi { get; set; }
        public string FiyatListeNo { get; set; }
        public string MaliyetMerkezNo { get; set; }
        public string YurtIciIthalat { get; set; }
        public string SiparisleIlgiliKisi { get; set; }
        public string TeslimYeri { get; set; }
    }
}
