//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaSiparisOnay
    {
        public int SiraNo { get; set; }
        public string SatinalmaSiparisNo { get; set; }
        public int SatinalmaSiparisSiraNo { get; set; }
        public string StokTuru { get; set; }
        public string SiparisTuru { get; set; }
        public string OnayTipi { get; set; }
        public string Onaylayan { get; set; }
        public System.DateTime OnayTarihi { get; set; }
    }
}
