//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinalmaSiparis
    {
        public string SatinalmaSiparisNo { get; set; }
        public short SiraNo { get; set; }
        public string StokTuru { get; set; }
        public string StokKodu { get; set; }
        public decimal Miktar1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string IslemGrubu { get; set; }
        public Nullable<System.DateTime> Termin { get; set; }
        public string TeslimYeri { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> KapatmaTarihi { get; set; }
        public string Kapatan { get; set; }
        public Nullable<decimal> ToleransYuzde { get; set; }
        public Nullable<System.DateTime> IptalTarihi { get; set; }
        public string IptalEden { get; set; }
        public string IptalNedeni { get; set; }
        public string KaliteKontroleTabimi { get; set; }
        public Nullable<decimal> KDVOrani { get; set; }
        public string KDVDahil { get; set; }
        public string OdemeSekli { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public string LotNo { get; set; }
        public string OlcuBirimi1 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string MDovizBirimi { get; set; }
        public string SatinalmaTeklifNo { get; set; }
        public Nullable<byte> SatinalmaTeklifSiraNo { get; set; }
        public string TeslimSekli { get; set; }
        public string NakliyeSekli { get; set; }
    }
}
