//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecimSQLAlanlari
    {
        public int SecimSQLAlanlariID { get; set; }
        public int SecimSQLleriID { get; set; }
        public string AlanAdi { get; set; }
        public byte SiraNo { get; set; }
        public int Genislik { get; set; }
        public bool Gorunsun { get; set; }
        public string KolonRengi { get; set; }
        public bool KolonBold { get; set; }
        public string Baslik0 { get; set; }
        public string Baslik1 { get; set; }
        public string Baslik2 { get; set; }
        public Nullable<int> KontrolID { get; set; }
    }
}
