//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sendika
    {
        public string IsyeriKodu { get; set; }
        public string SendikaKodu { get; set; }
        public string Adi { get; set; }
        public Nullable<double> Carpan { get; set; }
        public Nullable<double> Bolen { get; set; }
        public string UcretTuru { get; set; }
        public Nullable<double> Taban { get; set; }
        public Nullable<double> Tavan { get; set; }
        public Nullable<double> Sabit { get; set; }
    }
}
