//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenetKasasi
    {
        public int SenetKasasiID { get; set; }
        public string SenetKasasiKodu { get; set; }
        public string SenetKasasiAdi { get; set; }
        public string DovizBirimi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public System.DateTime DegistirilmeTarihi { get; set; }
        public string DegistirenKullaniciKodu { get; set; }
    }
}
