//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisArttirimTalep
    {
        public string SiparisNo { get; set; }
        public short SiparisSiraNo { get; set; }
        public short TalepSiraNo { get; set; }
        public Nullable<System.DateTime> TalepTarihi { get; set; }
        public string TalepNedeni { get; set; }
        public string TalepEden { get; set; }
        public Nullable<decimal> TalepMiktari { get; set; }
        public string Aciklama { get; set; }
        public string Onaylayan { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public string IptalEden { get; set; }
        public Nullable<System.DateTime> IptalTarihi { get; set; }
    }
}
