//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTur
    {
        public string SiparisTuru { get; set; }
        public string Aciklama { get; set; }
        public string SiparisTurGrubu { get; set; }
        public decimal MaxSiparisKatsayiMt { get; set; }
        public bool SipPartileTMiktarKontrol { get; set; }
    }
}
