//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisKapatma
    {
        public int SiraNo { get; set; }
        public string SiparisNo { get; set; }
        public int SiparisSiraNo { get; set; }
        public string StokTuru { get; set; }
        public string KapatmaTipi { get; set; }
        public string Kapatan { get; set; }
        public System.DateTime KapatmaTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
