//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTurOzelAlanlari
    {
        public string SiparisTuru { get; set; }
        public string OzelAlan1Adi { get; set; }
        public string OzelAlan2Adi { get; set; }
        public string OzelAlan3Adi { get; set; }
        public string OzelAlan4Adi { get; set; }
        public string OzelAlan5Adi { get; set; }
        public string OzelAlan6Adi { get; set; }
        public string OzelAlan7Adi { get; set; }
        public string OzelAlan8Adi { get; set; }
        public string OzelAlan9Adi { get; set; }
        public string OzelAlan10Adi { get; set; }
        public string OzelAlan1DosyaAdi { get; set; }
        public string OzelAlan2DosyaAdi { get; set; }
        public string OzelAlan3DosyaAdi { get; set; }
        public string OzelAlan4DosyaAdi { get; set; }
        public string OzelAlan5DosyaAdi { get; set; }
        public string OzelAlan6DosyaAdi { get; set; }
        public string OzelAlan7DosyaAdi { get; set; }
        public string OzelAlan8DosyaAdi { get; set; }
        public string OzelAlan9DosyaAdi { get; set; }
        public string OzelAlan10DosyaAdi { get; set; }
        public string OzelAlan1DosyaAlanAdi { get; set; }
        public string OzelAlan2DosyaAlanAdi { get; set; }
        public string OzelAlan3DosyaAlanAdi { get; set; }
        public string OzelAlan4DosyaAlanAdi { get; set; }
        public string OzelAlan5DosyaAlanAdi { get; set; }
        public string OzelAlan6DosyaAlanAdi { get; set; }
        public string OzelAlan7DosyaAlanAdi { get; set; }
        public string OzelAlan8DosyaAlanAdi { get; set; }
        public string OzelAlan9DosyaAlanAdi { get; set; }
        public string OzelAlan10DosyaAlanAdi { get; set; }
        public string OzelAlan11Adi { get; set; }
        public string OzelAlan12Adi { get; set; }
        public string OzelAlan13Adi { get; set; }
        public string OzelAlan14Adi { get; set; }
        public string OzelAlan15Adi { get; set; }
        public string OzelAlan11DosyaAdi { get; set; }
        public string OzelAlan12DosyaAdi { get; set; }
        public string OzelAlan13DosyaAdi { get; set; }
        public string OzelAlan14DosyaAdi { get; set; }
        public string OzelAlan15DosyaAdi { get; set; }
        public string OzelAlan11DosyaAlanAdi { get; set; }
        public string OzelAlan12DosyaAlanAdi { get; set; }
        public string OzelAlan13DosyaAlanAdi { get; set; }
        public string OzelAlan14DosyaAlanAdi { get; set; }
        public string OzelAlan15DosyaAlanAdi { get; set; }
        public bool OzelAlan1Zorunlu { get; set; }
        public bool OzelAlan2Zorunlu { get; set; }
        public bool OzelAlan3Zorunlu { get; set; }
        public bool OzelAlan4Zorunlu { get; set; }
        public bool OzelAlan5Zorunlu { get; set; }
        public bool OzelAlan6Zorunlu { get; set; }
        public bool OzelAlan7Zorunlu { get; set; }
        public bool OzelAlan8Zorunlu { get; set; }
        public bool OzelAlan9Zorunlu { get; set; }
        public bool OzelAlan10Zorunlu { get; set; }
        public bool OzelAlan11Zorunlu { get; set; }
        public bool OzelAlan12Zorunlu { get; set; }
        public bool OzelAlan13Zorunlu { get; set; }
        public bool OzelAlan14Zorunlu { get; set; }
        public bool OzelAlan15Zorunlu { get; set; }
    }
}
