//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTahsilat
    {
        public string SiparisNo { get; set; }
        public System.DateTime TahsilatTarihi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string DovizBirimi { get; set; }
        public string TahsilatTipi { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<decimal> KargoUcreti { get; set; }
        public Nullable<decimal> NavlunUcreti { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> SevkFisNo { get; set; }
    }
}
