//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisAna
    {
        public string SiparisNo { get; set; }
        public Nullable<System.DateTime> AlinmaTarihi { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public string CariNo { get; set; }
        public string SatinalmaSiparisNo { get; set; }
        public string IcDisSiparis { get; set; }
        public string SiparisTuru { get; set; }
        public string OzelKod { get; set; }
        public string Aciklama { get; set; }
        public string SiparisiAlan { get; set; }
        public string SiparisiVeren { get; set; }
        public string FiyatListeNo { get; set; }
        public string AkreditifNo { get; set; }
        public string Komisyoncu { get; set; }
        public Nullable<decimal> KomisyonYuzde { get; set; }
        public Nullable<decimal> KomisyonTutari { get; set; }
        public string KomisyonDovizBirimi { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public string Durum { get; set; }
        public Nullable<int> EtiketNo { get; set; }
        public string Komisyoncu2 { get; set; }
        public Nullable<decimal> KomisyonYuzde2 { get; set; }
        public Nullable<decimal> KomisyonTutari2 { get; set; }
        public string KomisyonDovizBirimi2 { get; set; }
        public string MenseiEtiketiIsteniyormu { get; set; }
        public string SevkOnayi { get; set; }
        public Nullable<int> HamEtiketNo { get; set; }
    }
}
