//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisOnayTip
    {
        public string StokTuru { get; set; }
        public string OnayTipi { get; set; }
        public string IlkOnaymi { get; set; }
        public string SonOnaymi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> OnaySiraNo { get; set; }
        public string BagliOnayTipi { get; set; }
    }
}
