//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlAnalizKosul
    {
        public int SqlNo { get; set; }
        public string FiltreAdi { get; set; }
        public string Sart { get; set; }
        public string FiltreTuru { get; set; }
    }
}
