//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlAnaliz
    {
        public int SqlNo { get; set; }
        public string SqlAdi { get; set; }
        public string ViewAdi { get; set; }
        public byte[] SqlText { get; set; }
        public Nullable<int> UstSqlNo { get; set; }
        public string GrafikX { get; set; }
        public string GrafikY { get; set; }
        public string GrafikTipi { get; set; }
        public string Grubu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Uyari { get; set; }
        public string UyariMailGidecekKullaniciKodu { get; set; }
    }
}
