//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnIkCalismaPozisyons
    {
        public int IkCalismaPozisyonId { get; set; }
        public int YakaTipi { get; set; }
        public string YakaTipiAdi { get; set; }
        public string CalismaPozisyonAdi { get; set; }
    }
}
