//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnLabAnalizCesits
    {
        public int LabAnalizCesitId { get; set; }
        public string LabAnalizCesitAdi { get; set; }
        public Nullable<int> MalzemeTipi { get; set; }
        public bool SeciliMi { get; set; }
        public string MalzemeAdi { get; set; }
        public int DegerTipi { get; set; }
        public string LabAnalizCesitAdiEng { get; set; }
        public Nullable<int> Sira { get; set; }
    }
}
