//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnOntefriks
    {
        public decimal OntefrikGrupId { get; set; }
        public decimal OntefrikId { get; set; }
        public string PartiNo { get; set; }
        public Nullable<int> Pozisyon { get; set; }
        public string HataNedeni { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> ToplamBobin { get; set; }
        public Nullable<int> KisaBobin { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string BirimAdi { get; set; }
        public string MakineNo { get; set; }
        public string StokAdi { get; set; }
    }
}
