//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnLabAnalizs
    {
        public int LabAnalizId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public Nullable<System.DateTime> IstenenTerminTarihi { get; set; }
        public Nullable<System.DateTime> PlanlananTerminTarihi { get; set; }
        public Nullable<System.DateTime> GerceklesenTerminTarihi { get; set; }
        public Nullable<int> AnalizTipi { get; set; }
        public int LabGrupId { get; set; }
        public string LabGrupAdi { get; set; }
        public int AnalizYapilacakBobinSayisi { get; set; }
        public int AnaliziYapilanBilesenSayisi { get; set; }
        public int AnalizYapilacakKumasSayisi { get; set; }
        public int ImalatAnalizYapilmaTipi { get; set; }
        public string Aciklama { get; set; }
        public string KayitYapanKulKodu { get; set; }
        public string KayitYapanKulAdi { get; set; }
        public int IsEmriNumarasiDurumu { get; set; }
        public string LabAciklama { get; set; }
        public int LabAnalizDurumu { get; set; }
        public string CariNo { get; set; }
        public int MakineId { get; set; }
        public int FirmaTipi { get; set; }
        public string CariAdi { get; set; }
        public string LabAnalizDurumuAdi { get; set; }
        public string PartiNo { get; set; }
        public string TakimSaati { get; set; }
        public string RefakartKartNo { get; set; }
        public string KutuNo { get; set; }
        public string BobinIciLotNo { get; set; }
        public Nullable<decimal> SevkMiktari { get; set; }
        public string SevkTarihi { get; set; }
        public string AnalizAdi { get; set; }
        public int BagliOlduguDosyaId { get; set; }
        public Nullable<System.DateTime> AnalizBaslangicSaati { get; set; }
        public Nullable<System.DateTime> AnalizBitisSaati { get; set; }
        public Nullable<int> KanalNo { get; set; }
        public Nullable<int> PartiAnaKlasorId { get; set; }
        public Nullable<int> DosyaTipi { get; set; }
        public string DosyaTipiAdi { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string BirimAdi { get; set; }
        public Nullable<int> AnalizYapilacakRenkCalismasi { get; set; }
    }
}
