//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnDenemeDosyaItems
    {
        public int DenemeDosyaItemId { get; set; }
        public int DenemeDosyaId { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public string DenemeAdi { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<int> MakineId { get; set; }
        public string MakineNo { get; set; }
        public string MakineAdi { get; set; }
        public string Aciklama { get; set; }
        public string IslemNo { get; set; }
        public string IslemTuru { get; set; }
    }
}
