//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnPaketlemeGunlukTalimatItems
    {
        public int PaketlemeGunlukTalimatItemId { get; set; }
        public int PaketlemeGunlukTalimatId { get; set; }
        public string TalimatBaslik { get; set; }
        public string TalimatIcerik { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int KayitYapanKulId { get; set; }
        public string KayitYapanKulAdi { get; set; }
        public Nullable<int> PartiAnaKlasorId { get; set; }
        public string PartiAdi { get; set; }
        public string GizlemeDurumu { get; set; }
    }
}
