//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnOntefrikGrups
    {
        public decimal OntefrikGrupId { get; set; }
        public string PartiNo { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string PersonelNo { get; set; }
        public string PersonelAdi { get; set; }
        public Nullable<int> ToplamBobinSayisi { get; set; }
        public Nullable<int> KisaBobinSayisi { get; set; }
    }
}
