//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnMailGrupKullanicis
    {
        public int MailGrupKullaniciId { get; set; }
        public int MailGrupId { get; set; }
        public string MailGrupAdi { get; set; }
        public int KullaniciId { get; set; }
        public string IsimSoyisim { get; set; }
    }
}
