//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnMusteriSikayetNumuneAnalizs
    {
        public int DosyaLabAnalizId { get; set; }
        public int LabAnalizId { get; set; }
        public int SikayetNumuneDosyaId { get; set; }
        public string CariAdi { get; set; }
        public System.DateTime LabAnalizKayitTarihi { get; set; }
        public int DosyaTipi { get; set; }
        public string DosyaAdi { get; set; }
    }
}
