//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnIplikOznitelikTipis
    {
        public int IplikOzNitelikTipi { get; set; }
        public string IplikOzNitelikTipiAdi { get; set; }
        public int IplikOzNitelikKategoriTipi { get; set; }
        public string IplikOzNitelikKategoriTipiAdi { get; set; }
    }
}
