//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnPartiSonuHarekets
    {
        public int PartiSonuHareketId { get; set; }
        public int PartiSonuTakipHareketTipi { get; set; }
        public string PartiSonuTakipHareketAdi { get; set; }
        public int PartiSonuTakipId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public Nullable<int> KayitYapanKulId { get; set; }
        public string KayitYapanKulAdi { get; set; }
    }
}
