//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnIkEgitimOturumSrcnKullanicis
    {
        public int EgitimOturumSrcnKullaniciId { get; set; }
        public int EgitimOturumId { get; set; }
        public string EgitimOturumAdi { get; set; }
        public int SrcnKullaniciId { get; set; }
        public string IsimSoyisim { get; set; }
        public int EgitimKatilimTanimId { get; set; }
        public string KatilimDurumAdi { get; set; }
    }
}
