//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnPartiSonuEkIslems
    {
        public int PartiSonuEkIslemId { get; set; }
        public Nullable<int> PartiSonuEkIslemTipi { get; set; }
        public string PartiSonuEkIslemAdi { get; set; }
        public int KayitYapanKulId { get; set; }
        public string KayitYapanKulAdi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int BirimId { get; set; }
        public string BirimAdi { get; set; }
        public int GonderilecekBobinSayisi { get; set; }
        public int IslemDurumu { get; set; }
        public int PartiSonuTakipId { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public int IadeYapanKulId { get; set; }
        public string IadeYapanKulAdi { get; set; }
    }
}
