//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnLabAnalizLogs
    {
        public int LabAnalizLogId { get; set; }
        public int LabAnalizId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string EskiDeger { get; set; }
        public string YeniDeger { get; set; }
        public string Aciklama { get; set; }
        public string Baslik { get; set; }
    }
}
