//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnPartiSonuTakips
    {
        public int PartiSonuTakipId { get; set; }
        public string RefakatNo { get; set; }
        public string PartiNo { get; set; }
        public int YapilacakPartiSonuIslemTipi { get; set; }
        public string YapilacakPartiSonuIslemTipiAdi { get; set; }
        public Nullable<int> KayitYapanKulId { get; set; }
        public string KayitYapanKulAdi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int BirimId { get; set; }
        public string BirimAdi { get; set; }
        public int PartiSonuTakipHareketTipi { get; set; }
        public string PartiSonuTakipHareketAdi { get; set; }
        public Nullable<System.DateTime> PartiKapatmaTarihi { get; set; }
        public Nullable<int> KapatanKulId { get; set; }
        public string KapatanKulAdi { get; set; }
        public bool SeciliMi { get; set; }
    }
}
