//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnLabAnalizItemAnalizCesitSonucs
    {
        public int LabAnalizItemAnalizCesitId { get; set; }
        public int LabAnalizItemId { get; set; }
        public int LabAnalizCesitId { get; set; }
        public string LabAnalizCesitAdi { get; set; }
        public string LabAnalizCesitAdiEng { get; set; }
        public decimal AnalizDegeri { get; set; }
        public string AnalizDegeriString { get; set; }
        public int DegerTipi { get; set; }
        public int YardimciTesisKontrolNoktaId { get; set; }
        public string YardimciTesisKontrolNoktaAdi { get; set; }
        public int MakinePozisyonNo { get; set; }
        public string IplikAdi { get; set; }
        public Nullable<int> IplikNo { get; set; }
        public string MusteriSikayetAnalizBaslik1 { get; set; }
        public string MusteriSikayetAnalizBaslik2 { get; set; }
        public string MusteriSikayetAnalizBaslik3 { get; set; }
        public string MusteriSikayetAnalizBaslik4 { get; set; }
        public string MusteriSikayetAnalizBaslik5 { get; set; }
    }
}
