//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnDosyaKonusmas
    {
        public int DosyaKonusmaId { get; set; }
        public int AnalizTipi { get; set; }
        public int BagliOlduguDosyaTipi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Aciklama { get; set; }
        public string KayitYapanKulKodu { get; set; }
        public string KayitYapanKulAdi { get; set; }
    }
}
