//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnToplantiRadevus
    {
        public int ToplantiRandevuId { get; set; }
        public int ToplantiSalonId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public Nullable<System.DateTime> ToplantiTarihi { get; set; }
        public string TalepEdenKulKodu { get; set; }
        public string TalepEdenKulAdi { get; set; }
        public string OnaylayanKulKodu { get; set; }
        public string OnaylayanKulAdi { get; set; }
        public string ToplantiBasligi { get; set; }
        public string ToplantiAciklamaca { get; set; }
        public int ToplantiRandevuDurumId { get; set; }
        public string ToplantiRandevuDurumAdi { get; set; }
    }
}
