//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SrcnPartiAltKlasors
    {
        public int PartiAltKlasorId { get; set; }
        public int PartiAltKlasorTipiId { get; set; }
        public string PartiAltKlasorTipAdi { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public int PartiAnaKlasorId { get; set; }
        public string PartiAdi { get; set; }
        public string PartiAltKlasorKodAdi { get; set; }
        public string KayitYapanKulAdi { get; set; }
        public Nullable<int> KayitYapanKulId { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string BirimAdi { get; set; }
    }
}
