//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokSayim
    {
        public int SayimNo { get; set; }
        public int SiraNo { get; set; }
        public string StokTuru { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string SeriNo { get; set; }
        public decimal Miktar1 { get; set; }
        public string OlcuBirimi1 { get; set; }
        public decimal Miktar2 { get; set; }
        public string OlcuBirimi2 { get; set; }
        public decimal Miktar3 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public string AmbarNo { get; set; }
        public string AmbarAdresi { get; set; }
        public string DokumanNo { get; set; }
    }
}
