//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public string StokAdi { get; set; }
        public string OlcuBirimi1 { get; set; }
        public string HamStokKodu { get; set; }
        public string OlcuBirimi2 { get; set; }
        public string OlcuBirimi3 { get; set; }
        public string StokTuru { get; set; }
        public string StokGrubu { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string DovizBirimi { get; set; }
        public string OnGorulenAmbarNo { get; set; }
        public string Kullanimdami { get; set; }
        public string OzelAlan1 { get; set; }
        public string OzelAlan2 { get; set; }
        public string OzelAlan3 { get; set; }
        public string OzelAlan4 { get; set; }
        public string OzelAlan5 { get; set; }
        public Nullable<decimal> MinimumStokDuzeyi { get; set; }
        public string CariAdi { get; set; }
        public string StokSinifi { get; set; }
        public string SayacKodu { get; set; }
        public Nullable<int> KayitSiraNo { get; set; }
        public string TicariStokKodu { get; set; }
        public string OzelAlan1OlcuBirimi { get; set; }
        public string OzelAlan2OlcuBirimi { get; set; }
        public string OzelAlan3OlcuBirimi { get; set; }
        public string OzelAlan4OlcuBirimi { get; set; }
        public string OzelAlan5OlcuBirimi { get; set; }
        public string OzelAlan6 { get; set; }
        public string OzelAlan7 { get; set; }
        public string OzelAlan8 { get; set; }
        public string OzelAlan9 { get; set; }
        public string OzelAlan10 { get; set; }
        public string OzelAlan6OlcuBirimi { get; set; }
        public string OzelAlan7OlcuBirimi { get; set; }
        public string OzelAlan8OlcuBirimi { get; set; }
        public string OzelAlan9OlcuBirimi { get; set; }
        public string OzelAlan10OlcuBirimi { get; set; }
        public Nullable<int> SiparisOnSuresi { get; set; }
        public Nullable<decimal> PartiBuyuklugu { get; set; }
        public string UretimRotaNo { get; set; }
        public string Resim { get; set; }
        public string OzelAlan11 { get; set; }
        public string OzelAlan12 { get; set; }
        public string OzelAlan13 { get; set; }
        public string OzelAlan14 { get; set; }
        public string OzelAlan15 { get; set; }
        public string OzelAlan11OlcuBirimi { get; set; }
        public string OzelAlan12OlcuBirimi { get; set; }
        public string OzelAlan13OlcuBirimi { get; set; }
        public string OzelAlan14OlcuBirimi { get; set; }
        public string OzelAlan15OlcuBirimi { get; set; }
        public string SonIslemTuru { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string TanimlayanKullaniciKodu { get; set; }
        public Nullable<decimal> En { get; set; }
        public Nullable<decimal> Boy { get; set; }
        public Nullable<decimal> Yukseklik { get; set; }
        public string ReferansStokKodu { get; set; }
        public string GTIPNo { get; set; }
        public Nullable<decimal> KDVYuzde { get; set; }
        public string BarKod { get; set; }
        public string Resim2 { get; set; }
        public string Aciklama { get; set; }
        public string TicariSayacKodu { get; set; }
        public Nullable<int> TicariKayitSiraNo { get; set; }
        public string TicariStokAdi { get; set; }
        public string TeknikOzellikParametreleri { get; set; }
        public string MaliyetRotaNo { get; set; }
        public string TeminSekli { get; set; }
        public string SatinalmaSekli { get; set; }
        public int SiparisTolerans { get; set; }
        public Nullable<System.DateTime> TanimlandigiTarih { get; set; }
        public string UygunTezgahTip { get; set; }
        public string Uyari { get; set; }
        public byte FaturayaEsasAlinanMiktar { get; set; }
        public string LotSayacKodu { get; set; }
        public Nullable<int> LotKayitSiraNo { get; set; }
        public string StokMuhasebeGrubu { get; set; }
        public Nullable<decimal> MaximumStokDuzeyi { get; set; }
        public string TedarikciTakvimKodu { get; set; }
        public Nullable<int> PartiKatsayisi { get; set; }
        public string KopyalandigiStokKodu { get; set; }
        public int SiparisOnSuresi2 { get; set; }
        public string IPSMalzemeGrubu { get; set; }
        public string UstStokKodu { get; set; }
        public string UretimLotNo { get; set; }
        public Nullable<int> UrunSablonID { get; set; }
        public string PaketlemeSekli { get; set; }
        public string DaraTipNo { get; set; }
    }
}
