//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokRezerv
    {
        public int SiraNo { get; set; }
        public string RezervStokKodu { get; set; }
        public string RezervLotNo { get; set; }
        public string RezervSeriNo { get; set; }
        public string SiparisNo { get; set; }
        public int SiparisSiraNo { get; set; }
        public decimal RezervMiktar1 { get; set; }
        public Nullable<decimal> RezervMiktar2 { get; set; }
        public Nullable<decimal> RezervMiktar3 { get; set; }
        public Nullable<System.DateTime> RezervTarihi { get; set; }
        public string PartiNo { get; set; }
        public Nullable<int> MakineMalzemeAtamaSiraNo { get; set; }
        public decimal FireMiktari { get; set; }
    }
}
