//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketIslemTip
    {
        public string IslemTipi { get; set; }
        public string IslemAciklama { get; set; }
        public string FisTuru { get; set; }
        public string GirisAmbarNo { get; set; }
        public string CikisAmbarNo { get; set; }
        public string CariNo { get; set; }
        public string Aciklama { get; set; }
        public string BelgeTuru { get; set; }
        public string BelgeNo { get; set; }
        public string FisiDuzenleyen { get; set; }
        public string SevkYeri { get; set; }
        public string NakliyeFirmasi { get; set; }
        public string StokTuru { get; set; }
    }
}
