//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKapaliUlkeler
    {
        public string StokKodu { get; set; }
        public string UlkeAdi { get; set; }
        public string CariNo { get; set; }
        public Nullable<System.DateTime> BaslangicGecerlilikTarihi { get; set; }
        public Nullable<System.DateTime> BitisGecerlilikTarihi { get; set; }
        public Nullable<System.DateTime> IlkSiparisTarihi { get; set; }
    }
}
