//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketOzelAlanDeger
    {
        public int FisNo { get; set; }
        public int SiraNo { get; set; }
        public string OzelAlan1Degeri { get; set; }
        public string OzelAlan2Degeri { get; set; }
        public string OzelAlan3Degeri { get; set; }
        public string OzelAlan4Degeri { get; set; }
        public string OzelAlan5Degeri { get; set; }
        public string OzelAlan6Degeri { get; set; }
        public string OzelAlan7Degeri { get; set; }
        public string OzelAlan8Degeri { get; set; }
        public string OzelAlan9Degeri { get; set; }
        public string OzelAlan10Degeri { get; set; }
        public string OzelAlan11Degeri { get; set; }
        public string OzelAlan12Degeri { get; set; }
        public string OzelAlan13Degeri { get; set; }
        public string OzelAlan14Degeri { get; set; }
        public string OzelAlan15Degeri { get; set; }
    }
}
