//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokRota
    {
        public string StokKodu { get; set; }
        public string RotaNo { get; set; }
        public short IslemSiraNo { get; set; }
        public string CikanStokKodu { get; set; }
    }
}
