//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TanimFormDetay
    {
        public int TanimFormDetayID { get; set; }
        public Nullable<int> TanimFormID { get; set; }
        public string AlanAdi { get; set; }
        public string AlanBaslik { get; set; }
        public string AlanTipi { get; set; }
        public string AlanTuru { get; set; }
        public Nullable<int> AlanBoyutu { get; set; }
        public Nullable<int> OndalikKarakter { get; set; }
        public int AlanGenisligi { get; set; }
        public Nullable<bool> ZorunluAlan { get; set; }
        public Nullable<bool> EssizAlan { get; set; }
        public Nullable<int> TabSiraNo { get; set; }
        public bool KolonGorunsun { get; set; }
        public Nullable<int> KolonGenislik { get; set; }
        public Nullable<int> KolonGrupSiraNo { get; set; }
        public Nullable<int> SecimSQLNo { get; set; }
        public string BaglantiTabloAdi { get; set; }
        public string BaglantiAlanAdi { get; set; }
        public bool BaglantiAlanDosyaYolSecim { get; set; }
    }
}
