//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarakRaporDetay
    {
        public int TarakRaporDetayID { get; set; }
        public Nullable<int> RaporSablonID { get; set; }
        public string RaporAdi { get; set; }
        public Nullable<int> Konum { get; set; }
        public Nullable<int> Deger { get; set; }
    }
}
