//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarakRaporSablon
    {
        public int TarakRaporSablonID { get; set; }
        public string RaporSablonAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> DegistirmeTarihi { get; set; }
        public Nullable<int> Birli { get; set; }
        public Nullable<int> Ikili { get; set; }
        public Nullable<int> Uclu { get; set; }
        public Nullable<int> Dortlu { get; set; }
        public Nullable<int> Besli { get; set; }
        public Nullable<int> Altili { get; set; }
        public Nullable<int> Yedili { get; set; }
        public Nullable<int> Sekizli { get; set; }
        public Nullable<int> Bos { get; set; }
        public Nullable<int> Toplam { get; set; }
        public Nullable<int> TarakNo { get; set; }
        public Nullable<int> ZeminTelAdedi { get; set; }
        public Nullable<decimal> ZeminTelEni { get; set; }
        public Nullable<int> ToplamDis { get; set; }
        public Nullable<decimal> OrtalamaSiklik { get; set; }
    }
}
