//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarakRapor
    {
        public int TarakRaporID { get; set; }
        public string RaporAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> TarakEni { get; set; }
        public Nullable<int> TarakNo { get; set; }
        public Nullable<int> DisliTelSayisi { get; set; }
        public Nullable<double> KenarUzunlugu { get; set; }
        public Nullable<int> KenarTelSayisi { get; set; }
        public Nullable<int> Toplam { get; set; }
        public Nullable<int> IstenenToplamTelSayisi { get; set; }
    }
}
