//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPeriyotKontrol
    {
        public string SiparisNo { get; set; }
        public int SiparisSiraNo { get; set; }
        public string PartiNo { get; set; }
        public double PeriyotMt { get; set; }
        public Nullable<double> NumuneUzunlugu { get; set; }
        public string NumuneAlan { get; set; }
        public Nullable<System.DateTime> NumuneAlimTarihi { get; set; }
    }
}
