//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezgahKumasDesen
    {
        public string DesenKodu { get; set; }
        public string DesenAdi { get; set; }
        public Nullable<int> JakarPlatinSayisi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> AtkiYonuRaporTekrari { get; set; }
        public string HavluMuBezMi { get; set; }
        public Nullable<decimal> CozguSiklik { get; set; }
        public Nullable<int> CozguRaporTelSayisi { get; set; }
        public Nullable<int> CozguTelAdedi1 { get; set; }
        public Nullable<int> CozguTelAdedi2 { get; set; }
        public Nullable<int> CozguTelAdedi3 { get; set; }
        public Nullable<int> CozguTelAdedi4 { get; set; }
        public Nullable<decimal> CozguSiklik1 { get; set; }
        public Nullable<decimal> CozguSiklik2 { get; set; }
        public Nullable<decimal> CozguSiklik3 { get; set; }
        public Nullable<decimal> CozguSiklik4 { get; set; }
        public string DisketKodu { get; set; }
        public Nullable<decimal> OrtZeminCozguSiklik { get; set; }
        public Nullable<System.DateTime> DesenOlusturmaTarihi { get; set; }
        public string DesenSahibi { get; set; }
        public Nullable<int> RapordakiKartonSayisi { get; set; }
        public Nullable<int> RapordakiTarakSayisi { get; set; }
        public string TasarimTesciliCiltNo { get; set; }
        public string DesenDaireNumarasi { get; set; }
        public string PersonelNo { get; set; }
        public string PersonelNo2 { get; set; }
        public string ZeminOrgu { get; set; }
        public string HavOrgu { get; set; }
        public decimal MKDesenRaporBoyu { get; set; }
        public decimal MKDesenRaporEni { get; set; }
        public decimal DuzeltmeKatsayisi { get; set; }
    }
}
