//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezgahKumasHavluBilgi
    {
        public string TezgahKumasKodu { get; set; }
        public string AtkiRaporTipi { get; set; }
        public Nullable<decimal> TeorikBoy { get; set; }
        public Nullable<decimal> FiiliBoy { get; set; }
    }
}
