//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezgahKumasSablon
    {
        public string TezgahKumasSablonNo { get; set; }
        public string TezgahKumasSablonAdi { get; set; }
        public string Aciklama { get; set; }
        public string UygunTezgah { get; set; }
        public Nullable<int> CozguRaporSablon1ID { get; set; }
        public Nullable<int> CozguRaporSablon2ID { get; set; }
        public Nullable<int> CozguRaporSablon3ID { get; set; }
        public Nullable<int> CozguRaporSablon4ID { get; set; }
    }
}
