//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TezgahKumasHavBilgileri
    {
        public string TezgahKumasKodu { get; set; }
        public string RaporTipi { get; set; }
        public string Harf { get; set; }
        public string StokKodu { get; set; }
        public string HavRaporu { get; set; }
        public decimal Yuzde { get; set; }
        public double Agirlik { get; set; }
    }
}
