//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferVeritabani
    {
        public int TransferVeritabaniID { get; set; }
        public string TransferAdi { get; set; }
        public string VeritabaniAdi { get; set; }
        public string ServerAdi { get; set; }
        public string Sifre { get; set; }
        public string KullaniciAdi { get; set; }
        public string IliskiliTicariProgram { get; set; }
    }
}
