//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimTestAsama
    {
        public string TestNo { get; set; }
        public string AsamaNo { get; set; }
        public string AsamaAdi { get; set; }
        public string TestCihazi { get; set; }
        public string IstenenDeger { get; set; }
        public string OlcuBirimi { get; set; }
        public string AltSinirDeger { get; set; }
        public string UstSinirDeger { get; set; }
        public string KaliteStandardi { get; set; }
        public string OrtamDegeri { get; set; }
        public string OrtamDegeriOlcuBirimi { get; set; }
        public string UygulamaTalimati { get; set; }
        public string Aciklama { get; set; }
        public string BaslangicOnayi { get; set; }
        public string FrekansiyelKontrol { get; set; }
        public string KontrolKarakteristigi { get; set; }
        public string KontrolFrenkansi { get; set; }
        public int AlanTipi { get; set; }
    }
}
