//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimHatalari
    {
        public string HataKodu { get; set; }
        public string HataAdi { get; set; }
        public string UretimMerkezNo { get; set; }
        public Nullable<int> StdDuzeltmeSuresi { get; set; }
        public string OzelKod1 { get; set; }
        public string OzelKod2 { get; set; }
        public string OzelKod3 { get; set; }
        public string HataTipi { get; set; }
        public string HataGrupKodu { get; set; }
        public Nullable<decimal> HataPuani1 { get; set; }
        public Nullable<decimal> HataPuani2 { get; set; }
        public Nullable<decimal> HataPuani3 { get; set; }
        public Nullable<decimal> HataPuani4 { get; set; }
        public Nullable<decimal> HataPuani5 { get; set; }
        public Nullable<decimal> HataPuani6 { get; set; }
    }
}
