//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimTest
    {
        public string TestNo { get; set; }
        public string TestAdi { get; set; }
        public string StdDeger { get; set; }
        public string KaliteStandardi { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public string StokTuru { get; set; }
    }
}
