//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimRotaAna
    {
        public string RotaNo { get; set; }
        public string RotaAdi { get; set; }
        public string DigerAdi { get; set; }
        public string Aciklama { get; set; }
        public string RotaTipi { get; set; }
        public string UretimRotaGrubu { get; set; }
        public string SayacKodu { get; set; }
        public bool CikanStokKoduBul { get; set; }
    }
}
