//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimHareket
    {
        public string RefakatKartNo { get; set; }
        public short SiraNo { get; set; }
        public int UretimSiraNo { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<short> SiparisSiraNo { get; set; }
        public string PartiNo { get; set; }
        public Nullable<System.DateTime> UretimBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> UretimBitisTarihi { get; set; }
        public string MakineNo { get; set; }
        public string RenkKodu { get; set; }
        public string ReceteNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public Nullable<decimal> Miktar2 { get; set; }
        public string CalisanPersonel1 { get; set; }
        public string CalisanPersonel2 { get; set; }
        public string CalisanPersonel3 { get; set; }
        public string IlaveReceteNo1 { get; set; }
        public string IlaveReceteNo2 { get; set; }
        public string IlaveReceteNo3 { get; set; }
        public string SeriNo { get; set; }
        public Nullable<decimal> Miktar3 { get; set; }
        public Nullable<decimal> UretimHizi { get; set; }
        public Nullable<int> GercekSure { get; set; }
    }
}
