//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimTestRaporAna
    {
        public int RaporNo { get; set; }
        public string RaporAdi { get; set; }
        public string RefakatNo { get; set; }
        public Nullable<short> IslemSiraNo { get; set; }
        public System.DateTime TestBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> TestBitisTarihi { get; set; }
        public string TestiYapan { get; set; }
        public string TestiOnaylayan { get; set; }
        public string TestSonucu { get; set; }
        public string KaliteKodu { get; set; }
        public string RaporResimAdresi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> SonKullanimTarihi { get; set; }
        public string SonKullaniciKodu { get; set; }
        public string StokKodu { get; set; }
    }
}
