//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunMaliyet
    {
        public string StokKodu { get; set; }
        public string MaliyetDonemi { get; set; }
        public string MaliyetAdi { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string DovizBirimi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string Aciklama { get; set; }
        public string KullanilanKur { get; set; }
    }
}
