//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VergiMuhasebeKodlari
    {
        public decimal VergiOrani { get; set; }
        public string AlisKDV { get; set; }
        public string SatisKDV { get; set; }
        public string AlisIadeKDV { get; set; }
        public string SatisIadeKDV { get; set; }
        public string AlimTevkifatKDV { get; set; }
        public string OdemeTevkifatKDV { get; set; }
        public string ABAlimKDV { get; set; }
        public string ABSatisKDV { get; set; }
        public string SatisOTV { get; set; }
        public string SatisIadeOTV { get; set; }
        public string SarfOTV { get; set; }
        public string FireOTV { get; set; }
        public string IndirilecekOTV { get; set; }
    }
}
