//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_STOK_DURUM_PTKS_TASD
    {
        public string IATOPartiNo { get; set; }
        public string StokAdi { get; set; }
        public string Kalite { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public string Firma { get; set; }
    }
}
