//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class YasalTanimlamalar
    {
        public string IsyeriKodu { get; set; }
        public Nullable<double> IsciAnalikNormal { get; set; }
        public Nullable<double> IsciHastalikNormal { get; set; }
        public Nullable<double> IsciMamullukNormal { get; set; }
        public Nullable<double> IsciIssizlikNormal { get; set; }
        public Nullable<double> IsciSgdpNormal { get; set; }
        public Nullable<double> IsciAnalikEmekli { get; set; }
        public Nullable<double> IsciHastalikEmekli { get; set; }
        public Nullable<double> IsciMalullukEmekli { get; set; }
        public Nullable<double> IsciSgdpEmekli { get; set; }
        public Nullable<double> IsciIssizlikEmekli { get; set; }
        public Nullable<double> IsciAnalikYabanci { get; set; }
        public Nullable<double> IsciHastalikYabanci { get; set; }
        public Nullable<double> IsciMamullukYabanci { get; set; }
        public Nullable<double> IsciIssizlikYabanci { get; set; }
        public Nullable<double> IsciAnalikCirak { get; set; }
        public Nullable<double> IsciHastalikCirak { get; set; }
        public Nullable<double> IsciMalullukCirak { get; set; }
        public Nullable<double> IsciIssizlikCirak { get; set; }
        public Nullable<double> IsverenAnalikNormal { get; set; }
        public Nullable<double> IsverenHastalikNormal { get; set; }
        public Nullable<double> IsverenMamullukNormal { get; set; }
        public Nullable<double> IsverenIssizlikNormal { get; set; }
        public Nullable<double> IsverenAnalikEmekli { get; set; }
        public Nullable<double> IsverenHastalikEmekli { get; set; }
        public Nullable<double> IsverenMalullukEmekli { get; set; }
        public Nullable<double> IsverenSgdpEmekli { get; set; }
        public Nullable<double> IsverenIssizlikEmekli { get; set; }
        public Nullable<double> IsverenAnalikYabanci { get; set; }
        public Nullable<double> IsverenHastalikYabanci { get; set; }
        public Nullable<double> IsverenMamullukYabanci { get; set; }
        public Nullable<double> IsverenIssizlikYabanci { get; set; }
        public Nullable<double> IsverenAnalikCirak { get; set; }
        public Nullable<double> IsverenHastalikCirak { get; set; }
        public Nullable<double> IsverenMalullukCirak { get; set; }
        public Nullable<double> IsverenIssizlikCirak { get; set; }
        public Nullable<double> IsciToplamSskKesintisiNormal { get; set; }
        public Nullable<double> IsciToplamSskKesintisiEmekli { get; set; }
        public Nullable<double> IsciToplamSskKesintisiYabanci { get; set; }
        public Nullable<double> IsciToplamSskKesintisiCirak { get; set; }
        public Nullable<double> IsverenTopSskKesintisiNormal { get; set; }
        public Nullable<double> IsverenTopSskKesintisiEmekli { get; set; }
        public Nullable<double> IsverenTopSskKesintisiYabanci { get; set; }
        public Nullable<double> IsverenTopSskKesintisiCirak { get; set; }
        public Nullable<double> AylikAsgariUcret { get; set; }
        public Nullable<double> SskTaban { get; set; }
        public Nullable<double> SskTavan { get; set; }
        public Nullable<double> KidemTazminatTavan { get; set; }
        public Nullable<double> DamgaVergisi { get; set; }
        public Nullable<double> SigortaMuafTavan { get; set; }
        public Nullable<double> OzelIndirim { get; set; }
        public Nullable<double> GocmenIndirimi { get; set; }
        public Nullable<double> SakatlikDegeri1 { get; set; }
        public Nullable<double> SakatlikDegeri2 { get; set; }
        public Nullable<double> SakatlikDegeri3 { get; set; }
        public Nullable<double> MaxSigortaMuafOrani { get; set; }
    }
}
