//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZzzMrvStokDetayTakip
    {
        public string AmbarNo { get; set; }
        public string AmbarAdi { get; set; }
        public string StokKodu { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> Miktar1 { get; set; }
        public string StokAdi { get; set; }
        public string OlcuBirimi1 { get; set; }
        public string StokTuru { get; set; }
    }
}
