//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZzzSrcnMakineIdli
    {
        public Nullable<int> BirimId { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> MakineId { get; set; }
        public string BolumAdi { get; set; }
        public string MakineNo { get; set; }
        public string MakineAdi { get; set; }
        public string MakineTuru { get; set; }
        public string MakineGrubu { get; set; }
        public string KanalSayisi { get; set; }
        public string BirimAdi { get; set; }
        public string UretimGrubu { get; set; }
    }
}
