//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZzzSrcnLottanOzelAlanaGecisler
    {
        public string PartiNo { get; set; }
        public string RefakatNo { get; set; }
        public string UretimTeknigi { get; set; }
        public Nullable<int> BirimId { get; set; }
        public Nullable<int> BolumId { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<int> MakineId { get; set; }
        public string MakineNo { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
        public string KanalSayisi { get; set; }
        public Nullable<System.DateTime> PlanlamaTermini { get; set; }
        public Nullable<int> IplikUretimTeknikId { get; set; }
    }
}
