//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyteks.Katman.DAL.Concrete.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZzzSrcnKullaniciCalismaPozisyonOzet
    {
        public int KullaniciId { get; set; }
        public string IsimSoyisim { get; set; }
        public byte[] Resim { get; set; }
        public string Birim { get; set; }
        public string Bolum { get; set; }
        public Nullable<int> Vardiya { get; set; }
        public Nullable<int> GrupId { get; set; }
        public string GrupAdi { get; set; }
        public string YakaTipiAdi { get; set; }
        public string CalismaPozisyonAdi { get; set; }
        public int GizlemeDurumu { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string PersonelKodu { get; set; }
    }
}
